; Collectible Entities
DEF CARROT          EQU 0
DEF HABANERO_CARROT EQU 1
DEF SUPER_CARROT    EQU 2
DEF CLAPBOARD_0     EQU 3
DEF CLAPBOARD_1     EQU 4
DEF CLAPBOARD_2     EQU 5
DEF CLAPBOARD_3     EQU 6
DEF TWEETY_E        EQU 7
DEF TWEETY_X        EQU 8
DEF TWEETY_T        EQU 9
DEF TWEETY_R        EQU 10
DEF TWEETY_A        EQU 11
DEF TWEETY_HEART    EQU 12
DEF TWEETY_1UP      EQU 13
