name BugsBarrel

metasprite
palettes 5 0
origin 1 20
mirrorx 9.5
slice 1 16
slice 9 16
slice 17 16
slice 1 32
slice 9 32
slice 17 32
slice 0 0
slice 8 0
slice 16 0

metasprite
palettes 5 0
origin 26 20
mirrorx 34.5
slice 26 16
slice 34 16
slice 42 16
slice 26 32
slice 34 32
slice 42 32
slice 25 0
slice 33 0
slice 41 0

metasprite
palettes 5 0
origin 51 20
mirrorx 59.5
slice 51 0
slice 59 0
slice 67 0
slice 51 16
slice 59 16
slice 67 16
slice 51 32
slice 59 32
slice 67 32
