name BugsTeleport

metasprite
palettes 5 0
origin -3 30
mirrorx -3

metasprite
palettes 5 0
origin -3 30
mirrorx 5.5
slice 0 32
slice 8 32
slice 3 0
slice 11 0
slice 3 16
slice 11 16
slice 16 32

metasprite
palettes 5 0
origin 21 30
mirrorx 29.5
slice 24 32
slice 32 32
slice 27 0
slice 35 0
slice 27 16
slice 35 16
slice 40 32

metasprite
palettes 5 0
origin 45 30
mirrorx 53.5
slice 48 32
slice 56 32
slice 51 0
slice 59 0
slice 51 16
slice 59 16
slice 64 32
