name LolaSkateboarding

metasprite
palettes 5 0
origin 8 31
mirrorx 8

metasprite
palettes 5 0
origin 8 31
mirrorx 16.5
slice 4 32
slice 12 32
slice 20 32
slice 28 32
slice_ignore_pixels 7 16 7 16 7 17 7 18 7 19
slice 15 16
slice 23 16
slice 8 0
slice 16 0
slice 0 6

metasprite
palettes 5 0
origin 44 31
mirrorx 52.5
slice 40 32
slice 48 32
slice 56 32
slice 64 32
slice 44 0
slice 52 0
slice 44 16
slice 52 16
slice 60 16
slice 36 3
