INCLUDE "hardware.inc"
INCLUDE "vram.asm"
INCLUDE "macros.asm"
INCLUDE "charmap.asm"
INCLUDE "constants.asm"

SECTION "ROM Bank $00", ROM0[$00]

Func_0:
	ld de, MBC5RomBank
	ld a, $06 ; TODO: Bank(?)
	ld [de], a
	ld a, [hli]
	ld [$dde9], a
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ret nz
	push hl
	ld a, Bank(Func_1a902)
	ld [de], a
	jp Func_1a902

; Adds a BCD value to the player's score.
; Input: c = value to add
AddScore:
	ld a, [hScore]
	add c
	daa
	ld [hScore], a
	ld a, [hScore + 1]
	adc b
	daa
	ld [hScore + 1], a
	ret

; Waits for VBlank period or immediately returns if LCD is disabled.
WaitUntilSafeToAccessVRAM:
	ld a, [rLCDC]
	add a
	ret nc ; return if LCD is disabled
	call WaitVBlank
	sub a
	ld [rLCDC], a
	ret

WaitHBlankStart:
	; Waits for the next HBlank period to begin.
	ld a, [rSTAT]
	and STATF_LCD
	jr z, WaitHBlankStart ; If we're already in the middle of HBlank, wait until it's over.
	; fallthrough

SECTION "rst 38", ROM0 [$38]

WaitNextHBlank_:
	ld a, [rSTAT]
	and STATF_LCD
	jr nz, WaitNextHBlank_
	ret

WaitNextHBlank:
	rst $38

; Hardware interrupts
SECTION "vblank", ROM0 [$40]
	reti

INCBIN "baserom.gbc", $41, $48 - $41

SECTION "hblank", ROM0 [$48]
	reti

INCBIN "baserom.gbc", $49, $50 - $49

SECTION "timer",  ROM0 [$50]
	reti

INCBIN "baserom.gbc", $51, $58 - $51

SECTION "serial", ROM0 [$58]
	reti

INCBIN "baserom.gbc", $59, $60 - $59

SECTION "joypad", ROM0 [$60]
	reti

SECTION "Home", ROM0 [$61]

INCBIN "baserom.gbc", $61, $68 - $61

; Waits until the VBlank period is entered.
WaitVBlank:
	ld a, [rLY]
	cp SCRN_Y + 1
	jr c, WaitVBlank
	ret

UpdateFrameCounter:
	ld a, [hPaused]
	and a
	ret nz
	ld hl, hFrameCounter
	inc [hl]
	ret

ResetFrameCounter:
	sub a
	ld [hFrameCounter], a
	ret

LoadCGBPalettesHome:
	ld a, Bank(LoadCGBPalettes)
	ld [MBC5RomBank], a
	jp LoadCGBPalettes

; The Warner Bros. Background banner graphics are only stored in ROM
; with the top-left quadrant. Since the other three quadrants are symmetric,
; this code unpacks the tiledata as such.
LoadWarnerBrosBannerQuadrants:
	push hl
	ld bc, $8830
	ld de, $8940
.asm_8b
	ld l, $09
.asm_8d
	ld a, [bc]
	inc bc
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	ld a, h
	ld [de], a
	inc de
	ld a, c
	and $0f
	jr nz, .asm_8d
	ld a, e
	sub $20
	ld e, a
	ld a, d
	sbc $00
	ld d, a
	dec l
	jr nz, .asm_8d
	ld a, c
	add $90
	ld c, a
	ld a, b
	adc $00
	ld b, a
	ld a, e
	add $b0
	ld e, a
	ld a, d
	adc $01
	ld d, a
	ld a, b
	cp $90
	jr nz, .asm_8b
	ld bc, $8830
	ld de, $96de
	ld h, $07
.asm_d7
	ld l, $12
.asm_d9
	ld a, [bc]
	inc bc
	ld [de], a
	inc de
	ld a, [bc]
	inc bc
	ld [de], a
	dec de
	dec de
	dec de
	ld a, c
	and $0f
	jr nz, .asm_d9
	ld a, e
	add $20
	ld e, a
	ld a, d
	adc $00
	ld d, a
	dec l
	jr nz, .asm_d9
	ld a, e
	sub $40
	ld e, a
	ld a, d
	sbc $02
	ld d, a
	dec h
	jr nz, .asm_d7
	pop hl
	ret

SECTION "Entry", ROM0 [$100]

Func_100:
	nop
	jp Start


SECTION "Header", ROM0 [$104]

	; The header is generated by rgbfix.
	; The space here is allocated to prevent code from being overwritten.
	ds $150 - $104

SECTION "Main", ROM0

Start:
	ld [hGameBoyColorDetection], a
Start_:
	di
	ld sp, wStack
	ld a, Bank(ResetInitialData)
	ld [MBC5RomBank], a
	call ResetInitialData
	call ResetPlayerData
	call Func_3e31
	call SetInitialScreen
	jp InitNextScreen

INCBIN "baserom.gbc", $16a, $322f - $16a

ResetPlayerData:
	ld a, [wDifficultySetting]
	ld bc, $505
	ld d, 4
	and a
	jr z, .setData
	ld bc, $404
	ld d, 3
.setData
	ld a, b
	ld [hCurHealth], a
	ld a, c
	ld [hMaxHealth], a
	ld a, d
	ld [hNumLives], a
	sub a
	ld [hScore], a
	ld [hScore + 1], a
	ret

INCBIN "baserom.gbc", $324e, $3d9e - $324e

WriteDMACodeToHRAM:
	ld hl, DMARoutine
	ld c, (hDMARoutine & $ff)
	ld b, 10
.loop
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .loop
	ld hl, wOAMBuffer
	ld b, wOAMBufferEnd - wOAMBuffer
	sub a
.clear
	ld [hli], a
	dec b
	jr nz, .clear
	call hDMARoutine
	sub a
	ld [$ff93], a
	ret

DMARoutine:
	ld a, wOAMBuffer >> 8
	ld [rDMA], a
	ld a, $28
.waitLoop
	dec a
	jr nz, .waitLoop
	ret

INCBIN "baserom.gbc", $3dc6, $3e13 - $3dc6

Func_3e13:
	ld a, Bank(Func_8053)
	ld [MBC5RomBank], a
	jp Func_8053

INCBIN "baserom.gbc", $3e1b, $3e31 - $3e1b

Func_3e31:
	sub a
	ld [$defe], a
	ld a, Bank(Func_8059)
	ld [MBC5RomBank], a
	jp Func_8059

INCBIN "baserom.gbc", $3e3d, $3e8b - $3e3d

InitNextScreen:
	sub a
	ld [hPaused], a
	ld sp, wStack
	call Func_3e13
	call WriteDMACodeToHRAM
	call WaitUntilSafeToAccessVRAM
	ld hl, wCurScreen
	inc [hl]
	ld a, [hl]
	add a
	ld c, a
	ld b, $00
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ld hl, Data_1af94
	jr nz, .load
	ld hl, Data_1b030
.load
	add hl, bc
	ld a, Bank(Data_1af94)
	ld [MBC5RomBank], a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	or h
	jp z, Start_
	call LoadData
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push bc
	ret

SetInitialScreen:
	sub a
	ld [wCurScreen], a
	ret

INCLUDE "home/load.asm"

INCBIN "baserom.gbc", $3ff1, $4000 - $3ff1

SECTION "ROM Bank $01", ROMX[$4000], BANK[$1]

INCBIN "baserom.gbc", $4000, $7dfc - $4000

ResetInitialData:
	call WaitUntilSafeToAccessVRAM
	sub a
	ld [rIF], a
	ld [$ffff], a
	ld [rSC], a
	ld [rTAC], a
	ld [rSTAT], a
	ld a, $30
	ld [rP1], a
	ld hl, vTilesOB
	ld bc, $2000
	call ClearData
	ld hl, wRAMStart
	ld bc, wStack - wRAMStart - 4
	call ClearData
	ld hl, _HRAM
	ld bc, $7e
	call ClearData
	sub a
	ld [$deec], a
	ld [wDifficultySetting], a
	ld [$deb6], a
	ld [$dde8], a
	ld hl, wPasswordCharacters
	ld [hli], a
	ld [hli], a
	ld [hl], a
	ret

; Fills a data region with 0 values.
; Input: hl = destination
;        bc = number of bytes to clear
ClearData:
	sub a
	ld [hli], a
	dec bc
	ld a, c
	or b
	jr nz, ClearData
	ret

INCBIN "baserom.gbc", $7e45, $8000 - $7e45

SECTION "ROM Bank $02", ROMX[$4000], BANK[$2]

INCBIN "baserom.gbc", $8000, $8053 - $8000

Func_8053:
	jp Func_853d

INCBIN "baserom.gbc", $8056, $8059 - $8056

Func_8059:
	jp Func_8522

INCBIN "baserom.gbc", $805c, $8522 - $805c

Func_8522:
	ld a, $ff
	ld [rNR52], a
	ld a, $70
	ld [$db4b], a
	ld a, $c5
	ld [$db4a], a
	xor a
	ld [$db45], a
	ld [$db42], a
	ld [$db47], a
	ld [$db5d], a
Func_853d:
	ld a, $70
	ld [$db49], a
	ld a, $20
	ld [$db48], a
	xor a
	ld [rNR12], a
	ld [rNR22], a
	ld [rNR32], a
	ld [rNR42], a
	ld [rNR14], a
	ld [rNR24], a
	ld [rNR34], a
	ld [rNR44], a
	ld [$db65], a
	ld [$db52], a
	ld [$db5c], a
	ld a, $88
	ld [$db46], a
	ld a, $77
	ld [rNR50], a
	ld h, $db
	call .asm_857b
	inc h
	call .asm_857b
	inc h
	call .asm_857b
	inc h
	jr .asm_857b
	pop af
.asm_857b
	ld a, h
	cp $de
	jr z, .asm_85aa
	xor a
	ld l, $38
	ld [hl], $11
	dec l
	ld [hl], a
	ld l, $27
	ld [hl], a
	ld l, $08
	ld [hl], a
	ld l, $04
	ld [hl], a
	ld l, $2f
	ld [hl], a
	ld l, $2c
	ld [hl], a
	ld l, $37
	ld [hl], a
	ld l, $0f
	ld [hld], a
	ld [hld], a
	ld [hl], $f4
	dec l
	dec l
	ld [hld], a
	inc a
	ld [hl], a
	ld l, $33
	ld [hld], a
	dec a
	ld [hl], a
	ret
.asm_85aa
	xor a
	ld [$de27], a
	ld [$de08], a
	ld [$db5e], a
	ld [$db5f], a
	dec a
	ld [$db44], a
	jp Func_876e

INCBIN "baserom.gbc", $85be, $876e - $85be

Func_876e:
	xor a
	ld [rNR30], a
	ld c, (_AUD3WAVERAM & $ff)
	ld hl, $db4c
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hl]
	ld [$ff00+c], a
	ld a, [$db42]
	and a
	ret nz
	ld a, $80
	ld [$dd07], a
	ld [rNR30], a
	ld [rNR34], a
	ret

INCBIN "baserom.gbc", $87b7, $C000 - $87b7

SECTION "ROM Bank $03", ROMX[$4000], BANK[$3]

WarnerBrosCopyrightLogoTiles:
	INCBIN "gfx/warner_bros_copyright/logo.interleave.2bpp.lz"
WarnerBrosCopyrightTrademarkTiles:
	INCBIN "gfx/warner_bros_copyright/trademark.2bpp.lz"
WarnerBrosCopyrightLolaBunnyTiles:
	INCBIN "gfx/warner_bros_copyright/lola_bunny.2bpp.lz"

INCBIN "baserom.gbc", $c765, $ccff - $c765

FarmSceneTiles:
	INCBIN "gfx/titlescreen/background.2bpp.lz"

INCBIN "baserom.gbc", $d674, $da76 - $d674

InfogramesCopyrightTiles:
	INCBIN "gfx/infogrames_copyright/background.2bpp.lz"

INCBIN "baserom.gbc", $dc9f, $10000 - $dc9f

SECTION "ROM Bank $04", ROMX[$4000], BANK[$4]

INCBIN "baserom.gbc", $10000, $14000 - $10000

SECTION "ROM Bank $05", ROMX[$4000], BANK[$5]

INCBIN "baserom.gbc", $14000, $16e8c - $14000

INCLUDE "data/passwords.asm"

INCBIN "baserom.gbc", $16eab, $17dd6 - $16eab

SECTION "ROM Bank $06", ROMX[$4000], BANK[$6]

INCBIN "baserom.gbc", $18000, $1a89f - $18000

; Loads common sprite palettes and the specified BG and
; sprite palettes. Also clears the BG map attributes.
; Input: hl = pointer to palette data structure
LoadCGBPalettes:
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ret nz
	ld a, (1 << 7) | $28
	ld [rOCPS], a
	ld de, CommonSpritePalettes
	ld b, 3 ; number of palettes
.commonSpritePaletteLoop
	ld c, 6 ; number of color bytes
	sub a
	ld [rOCPD], a ; First two bytes are the transparent color in the sprite palette.
	ld [rOCPD], a
.commonSpriteColorLoop
	ld a, [de]
	inc de
	ld [rOCPD], a
	dec c
	jr nz, .commonSpriteColorLoop
	dec b
	jr nz, .commonSpritePaletteLoop
	ld a, $80
	ld [rBCPS], a
	ld a, [hli]
	ld b, a ; number of palettes
.backgroundPaletteLoop
	ld a, b
	and a
	jr z, .loadSpritePalettes
	dec b
	ld c, 8
.backgroundColorLoop
	ld a, [hli]
	ld [rBCPD], a
	dec c
	jr nz, .backgroundColorLoop
	jr .backgroundPaletteLoop
.loadSpritePalettes
	ld a, $80
	ld [rOCPS], a
	ld a, [hli]
	ld b, a
.spritePaletteLoop
	ld a, b
	and a
	jr z, .clearBank1BGMap
	dec b
	ld c, 6 ; number of color bytes
	sub a
	ld [rOCPD], a ; First two bytes are the transparent color in the sprite palette.
	ld [rOCPD], a
.spriteColorLoop
	ld a, [hli]
	ld [rOCPD], a
	dec c
	jr nz, .spriteColorLoop
	jr .spritePaletteLoop
.clearBank1BGMap
	ld a, 1
	ld [rVBK], a
	ld hl, vBGMap
	ld bc, $800
.clearLoop
	sub a
	ld [hli], a
	dec bc
	ld a, c
	or b
	jr nz, .clearLoop
	sub a
	ld [rVBK], a
	ret

Func_1a902:
	ld h, b
	ld l, c
	ld a, $80
	ld [rBCPS], a
	ld a, [hli]
	ld b, a
.paletteLoop
	ld a, b
	and a
	jr z, .done
	dec b
	ld c, 8
.colorLoop
	ld a, [hli]
	ld [rBCPD], a
	dec c
	jr nz, .colorLoop
	jr .paletteLoop
.done
	call ReadAndLoadCGBpalettes
	pop hl
	ret

ReadAndLoadCGBpalettes:
	ld a, [hli]
	ld h, [hl]
	ld l, a
	jp LoadCGBPalettesHome

INCBIN "baserom.gbc", $1a924, $1af18 - $1a924

; This only holds colors 1-3. The first transparent color is hardcoded
; in LoadCGBPalettes.
CommonSpritePalettes:
	; OBJ Palette 5
	RGB(31, 31, 31)
	RGB(14, 14, 14)
	RGB(0, 0, 0)

	; OBJ Palette 6
	RGB(31, 27, 0)
	RGB(19, 7, 0)
	RGB(0, 0, 0)

	; OBJ Palette 7
	RGB(31, 28, 20)
	RGB(31, 8, 0)
	RGB(0, 0, 0)

INCBIN "baserom.gbc", $1af2a, $1af94 - $1af2a

Data_1af94:
	dw $ffff
	dw Data_1b0cc ; SCREEN_COPYRIGHT_INFOGRAMES
	dw $70d9 ; SCREEN_COPYRIGHT_WARNER_BROS
	dw $7129 ; SCREEN_LANGUAGE_SELECT
	dw $716f ; SCREEN_TITLESCREEN
	dw $7147 ; SCREEN_OPTIONS
	dw $7194 ; SCREEN_INTRO_SCENE
	dw $72ee ; SCREEN_STUDIO_ENTRANCE
	dw $71fc ; SCREEN_TREASURE_ISLAND_1_INTRO
	dw $73b6 ; SCREEN_TREASURE_ISLAND_1
	dw $7722 ; SCREEN_TREASURE_ISLAND_1_SUMMARY
	dw $7794 ; SCREEN_TREASURE_ISLAND_1_BONUS
	dw $720d ; SCREEN_TREASURE_ISLAND_2_INTRO
	dw $73ed ; SCREEN_TREASURE_ISLAND_2
	dw $7722 ; SCREEN_TREASURE_ISLAND_2_SUMMARY
	dw $779b ; SCREEN_TREASURE_ISLAND_2_BONUS
	dw $721e ; SCREEN_TREASURE_ISLAND_BOSS_INTRO
	dw $7472 ; SCREEN_TREASURE_ISLAND_BOSS
	dw $7722 ; SCREEN_TREASURE_ISLAND_BOSS_SUMMARY
	dw $77a2 ; SCREEN_TREASURE_ISLAND_BOSS_BONUS
	dw $7710 ; SCREEN_PASSWORD_1
	dw $7300 ; SCREEN_STUDIO_TREASURE_ISLAND
	dw $71c9 ; SCREEN_CRAZY_TOWN_1_INTRO
	dw $7348 ; SCREEN_CRAZY_TOWN_1
	dw $7722 ; SCREEN_CRAZY_TOWN_1_SUMMARY
	dw $77a9 ; SCREEN_CRAZY_TOWN_1_BONUS
	dw $71da ; SCREEN_CRAZY_TOWN_2_INTRO
	dw $737f ; SCREEN_CRAZY_TOWN_2
	dw $7722 ; SCREEN_CRAZY_TOWN_2_SUMMARY
	dw $77b0 ; SCREEN_CRAZY_TOWN_2_BONUS
	dw $71eb ; SCREEN_CRAZY_TOWN_BOSS_INTRO
	dw $7424 ; SCREEN_CRAZY_TOWN_BOSS
	dw $7722 ; SCREEN_CRAZY_TOWN_BOSS_SUMMARY
	dw $77b7 ; SCREEN_CRAZY_TOWN_BOSS_BONUS
	dw $7312 ; SCREEN_STUDIO_CRAZY_TOWN
	dw $722f ; SCREEN_TAZ_ZOO_1_INTRO
	dw $74c0 ; SCREEN_TAZ_ZOO_1
	dw $7722 ; SCREEN_TAZ_ZOO_1_SUMMARY
	dw $77be ; SCREEN_TAZ_ZOO_1_BONUS
	dw $7240 ; SCREEN_TAZ_ZOO_2_INTRO
	dw $74f7 ; SCREEN_TAZ_ZOO_2
	dw $7722 ; SCREEN_TAZ_ZOO_2_SUMMARY
	dw $77c5 ; SCREEN_TAZ_ZOO_2_BONUS
	dw $7251 ; SCREEN_TAZ_ZOO_BOSS_INTRO
	dw $752e ; SCREEN_TAZ_ZOO_BOSS
	dw $7722 ; SCREEN_TAZ_ZOO_BOSS_SUMMARY
	dw $77cc ; SCREEN_TAZ_ZOO_BOSS_BONUS
	dw $7719 ; SCREEN_PASSWORD_2
	dw $7324 ; SCREEN_STUDIO_TAZ_ZOO
	dw $7262 ; SCREEN_SPACE_STATION_1_INTRO
	dw $7588 ; SCREEN_SPACE_STATION_1
	dw $7722 ; SCREEN_SPACE_STATION_1_SUMMARY
	dw $77d3 ; SCREEN_SPACE_STATION_1_BONUS
	dw $7273 ; SCREEN_SPACE_STATION_2_INTRO
	dw $75bf ; SCREEN_SPACE_STATION_2
	dw $7722 ; SCREEN_SPACE_STATION_2_SUMMARY
	dw $77da ; SCREEN_SPACE_STATION_2_BONUS
	dw $7284 ; SCREEN_SPACE_STATION_BOSS_INTRO
	dw $75f6 ; SCREEN_SPACE_STATION_BOSS
	dw $7722 ; SCREEN_SPACE_STATION_BOSS_SUMMARY
	dw $77e1 ; SCREEN_SPACE_STATION_BOSS_BONUS
	dw $7336 ; SCREEN_STUDIO_SPACE_STATION
	dw $7295 ; SCREEN_FUDD_FOREST_1_INTRO
	dw $7638 ; SCREEN_FUDD_FOREST_1
	dw $7722 ; SCREEN_FUDD_FOREST_1_SUMMARY
	dw $77e8 ; SCREEN_FUDD_FOREST_1_BONUS
	dw $72a6 ; SCREEN_FUDD_FOREST_2_INTRO
	dw $766f ; SCREEN_FUDD_FOREST_2
	dw $7722 ; SCREEN_FUDD_FOREST_2_SUMMARY
	dw $77ef ; SCREEN_FUDD_FOREST_2_BONUS
	dw $72b7 ; SCREEN_FUDD_FOREST_BOSS_INTRO
	dw $76a6 ; SCREEN_FUDD_FOREST_BOSS
	dw $7722 ; SCREEN_FUDD_FOREST_BOSS_SUMMARY
	dw $7764 ; SCREEN_PROLOGUE_SCENE
	dw $777d ; SCREEN_CREDITS
	dw $0000
	dw $7113 ; SCREEN_GAME_OVER
	dw $0000

Data_1b030:
	dw $ffff
	dw $7cb0 ; SCREEN_COPYRIGHT_INFOGRAMES
	dw $70d9 ; SCREEN_COPYRIGHT_WARNER_BROS
	dw $7129 ; SCREEN_LANGUAGE_SELECT
	dw $7c63 ; SCREEN_TITLESCREEN
	dw $7147 ; SCREEN_OPTIONS
	dw $7c8d ; SCREEN_INTRO_SCENE
	dw $72ee ; SCREEN_STUDIO_ENTRANCE
	dw $71fc ; SCREEN_TREASURE_ISLAND_1_INTRO
	dw $7891 ; SCREEN_TREASURE_ISLAND_1
	dw $7722 ; SCREEN_TREASURE_ISLAND_1_SUMMARY
	dw $7794 ; SCREEN_TREASURE_ISLAND_1_BONUS
	dw $720d ; SCREEN_TREASURE_ISLAND_2_INTRO
	dw $78cd ; SCREEN_TREASURE_ISLAND_2
	dw $7722 ; SCREEN_TREASURE_ISLAND_2_SUMMARY
	dw $779b ; SCREEN_TREASURE_ISLAND_2_BONUS
	dw $721e ; SCREEN_TREASURE_ISLAND_BOSS_INTRO
	dw $79d9 ; SCREEN_TREASURE_ISLAND_BOSS
	dw $7722 ; SCREEN_TREASURE_ISLAND_BOSS_SUMMARY
	dw $77a2 ; SCREEN_TREASURE_ISLAND_BOSS_BONUS
	dw $7710 ; SCREEN_PASSWORD_1
	dw $7300 ; SCREEN_STUDIO_TREASURE_ISLAND
	dw $71c9 ; SCREEN_CRAZY_TOWN_1_INTRO
	dw $7819 ; SCREEN_CRAZY_TOWN_1
	dw $7722 ; SCREEN_CRAZY_TOWN_1_SUMMARY
	dw $77a9 ; SCREEN_CRAZY_TOWN_1_BONUS
	dw $71da ; SCREEN_CRAZY_TOWN_2_INTRO
	dw $7855 ; SCREEN_CRAZY_TOWN_2
	dw $7722 ; SCREEN_CRAZY_TOWN_2_SUMMARY
	dw $77b0 ; SCREEN_CRAZY_TOWN_2_BONUS
	dw $71eb ; SCREEN_CRAZY_TOWN_BOSS_INTRO
	dw $7909 ; SCREEN_CRAZY_TOWN_BOSS
	dw $7722 ; SCREEN_CRAZY_TOWN_BOSS_SUMMARY
	dw $77b7 ; SCREEN_CRAZY_TOWN_BOSS_BONUS
	dw $7312 ; SCREEN_STUDIO_CRAZY_TOWN
	dw $722f ; SCREEN_TAZ_ZOO_1_INTRO
	dw $7961 ; SCREEN_TAZ_ZOO_1
	dw $7722 ; SCREEN_TAZ_ZOO_1_SUMMARY
	dw $77be ; SCREEN_TAZ_ZOO_1_BONUS
	dw $7240 ; SCREEN_TAZ_ZOO_2_INTRO
	dw $799d ; SCREEN_TAZ_ZOO_2
	dw $7722 ; SCREEN_TAZ_ZOO_2_SUMMARY
	dw $77c5 ; SCREEN_TAZ_ZOO_2_BONUS
	dw $7251 ; SCREEN_TAZ_ZOO_BOSS_INTRO
	dw $7bcd ; SCREEN_TAZ_ZOO_BOSS
	dw $7722 ; SCREEN_TAZ_ZOO_BOSS_SUMMARY
	dw $77cc ; SCREEN_TAZ_ZOO_BOSS_BONUS
	dw $7719 ; SCREEN_PASSWORD_2
	dw $7324 ; SCREEN_STUDIO_TAZ_ZOO
	dw $7262 ; SCREEN_SPACE_STATION_1_INTRO
	dw $7a35 ; SCREEN_SPACE_STATION_1
	dw $7722 ; SCREEN_SPACE_STATION_1_SUMMARY
	dw $77d3 ; SCREEN_SPACE_STATION_1_BONUS
	dw $7273 ; SCREEN_SPACE_STATION_2_INTRO
	dw $7a71 ; SCREEN_SPACE_STATION_2
	dw $7722 ; SCREEN_SPACE_STATION_2_SUMMARY
	dw $77da ; SCREEN_SPACE_STATION_2_BONUS
	dw $7284 ; SCREEN_SPACE_STATION_BOSS_INTRO
	dw $7aad ; SCREEN_SPACE_STATION_BOSS
	dw $7722 ; SCREEN_SPACE_STATION_BOSS_SUMMARY
	dw $77e1 ; SCREEN_SPACE_STATION_BOSS_BONUS
	dw $7336 ; SCREEN_STUDIO_SPACE_STATION
	dw $7295 ; SCREEN_FUDD_FOREST_1_INTRO
	dw $7afb ; SCREEN_FUDD_FOREST_1
	dw $7722 ; SCREEN_FUDD_FOREST_1_SUMMARY
	dw $77e8 ; SCREEN_FUDD_FOREST_1_BONUS
	dw $72a6 ; SCREEN_FUDD_FOREST_2_INTRO
	dw $7b37 ; SCREEN_FUDD_FOREST_2
	dw $7722 ; SCREEN_FUDD_FOREST_2_SUMMARY
	dw $77ef ; SCREEN_FUDD_FOREST_2_BONUS
	dw $72b7 ; SCREEN_FUDD_FOREST_BOSS_INTRO
	dw $7b73 ; SCREEN_FUDD_FOREST_BOSS
	dw $7722 ; SCREEN_FUDD_FOREST_BOSS_SUMMARY
	dw $7cc2 ; SCREEN_PROLOGUE_SCENE
	dw $777d ; SCREEN_CREDITS
	dw $0000
	dw $7113 ; SCREEN_GAME_OVER
	dw $0000

Data_1b0cc:
	db $03
	dw $5A76
	dw $9550

	db $0E
	dw $7F94
	dw $9800

	db $FF ; terminator
	dw $04F8

INCBIN "baserom.gbc", $1b0d9, $1bcb0 - $1b0d9

Data_1bcb0:
	db $16
	dw $5d9d
	dw $9550

	db $16
	dw $5fc2
	dw $9800

	db $16
	dw $6021
	dw $d9d5

	db $FF

INCBIN "baserom.gbc", $1bcc0, $1c000 - $1bcc0

SECTION "ROM Bank $07", ROMX[$4000], BANK[$7]

INCBIN "baserom.gbc", $1C000, $20000 - $1C000

SECTION "ROM Bank $08", ROMX[$4000], BANK[$8]

INCBIN "baserom.gbc", $20000, $24000 - $20000

SECTION "ROM Bank $09", ROMX[$4000], BANK[$9]

INCBIN "baserom.gbc", $24000, $27c51 - $24000

WarnerBrosCopyrightEdgeTiles:
	INCBIN "gfx/warner_bros_copyright/edge.2bpp.lz"

INCBIN "baserom.gbc", $27ced, $28000 - $27ced

SECTION "ROM Bank $0A", ROMX[$4000], BANK[$A]

INCBIN "baserom.gbc", $28000, $2C000 - $28000

SECTION "ROM Bank $0B", ROMX[$4000], BANK[$B]

INCBIN "baserom.gbc", $2C000, $30000 - $2C000

SECTION "ROM Bank $0C", ROMX[$4000], BANK[$C]

INCBIN "baserom.gbc", $30000, $34000 - $30000

SECTION "ROM Bank $0D", ROMX[$4000], BANK[$D]

INCBIN "baserom.gbc", $34000, $38000 - $34000

SECTION "ROM Bank $0E", ROMX[$4000], BANK[$E]

INCBIN "baserom.gbc", $38000, $3bd22 - $38000

WarnerBrosCopyrightBugsBunnyTiles:
	INCBIN "gfx/warner_bros_copyright/bugs_bunny.2bpp.lz"

InfogramesCopyrightTilemap:
	INCBIN "gfx/infogrames_copyright/background.tilemap.lz"

SECTION "ROM Bank $0F", ROMX[$4000], BANK[$F]

INCBIN "baserom.gbc", $3C000, $3fceb - $3C000

WarnerBrosCopyrightTiles:
	INCBIN "gfx/warner_bros_copyright/background.2bpp.lz"

INCBIN "baserom.gbc", $3ff8c, $40000 - $3ff8c

SECTION "ROM Bank $10", ROMX[$4000], BANK[$10]

INCBIN "baserom.gbc", $40000, $44000 - $40000

SECTION "ROM Bank $11", ROMX[$4000], BANK[$11]

INCBIN "baserom.gbc", $44000, $48000 - $44000

SECTION "ROM Bank $12", ROMX[$4000], BANK[$12]

INCBIN "baserom.gbc", $48000, $4C000 - $48000

SECTION "ROM Bank $13", ROMX[$4000], BANK[$13]

INCBIN "baserom.gbc", $4C000, $50000 - $4C000

SECTION "ROM Bank $14", ROMX[$4000], BANK[$14]

INCBIN "baserom.gbc", $50000, $54000 - $50000

SECTION "ROM Bank $15", ROMX[$4000], BANK[$15]

INCBIN "baserom.gbc", $54000, $58000 - $54000

SECTION "ROM Bank $16", ROMX[$4000], BANK[$16]

INCBIN "baserom.gbc", $58000, $59d9d - $58000

InfogramesCopyrightGBCTiles:
	INCBIN "gfx/infogrames_copyright/background_gbc.2bpp.lz"
InfogramesCopyrightGBCTilemap:
	INCBIN "gfx/infogrames_copyright/background_gbc.tilemap.lz"
InfogramesCopyrightGBCAttributesTilemap:
	INCBIN "gfx/infogrames_copyright/background_gbc.attrmap.lz"

SECTION "ROM Bank $20", ROMX[$4000], BANK[$20]
; force 1MB ROM
