INCLUDE "hardware.inc"
INCLUDE "vram.asm"
INCLUDE "macros.asm"
INCLUDE "charmap.asm"
INCLUDE "constants.asm"

SECTION "ROM Bank $00", ROM0[$00]

Func_0:
	ld de, MBC5RomBank
	ld a, $06 ; TODO: Bank(?)
	ld [de], a
	ld a, [hli]
	ld [$dde9], a
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ret nz
	push hl
	ld a, Bank(Func_1a902)
	ld [de], a
	jp Func_1a902

; Adds a BCD value to the player's score.
; Input: c = value to add
AddScore:
	ld a, [hScore]
	add c
	daa
	ld [hScore], a
	ld a, [hScore + 1]
	adc b
	daa
	ld [hScore + 1], a
	ret

; Waits for VBlank period or immediately returns if LCD is disabled.
WaitUntilSafeToAccessVRAM:
	ld a, [rLCDC]
	add a
	ret nc ; return if LCD is disabled
	call WaitVBlank
	sub a
	ld [rLCDC], a
	ret

WaitHBlankStart:
	; Waits for the next HBlank period to begin.
	ld a, [rSTAT]
	and STATF_LCD
	jr z, WaitHBlankStart ; If we're already in the middle of HBlank, wait until it's over.
	; fallthrough

SECTION "rst 38", ROM0 [$38]

WaitNextHBlank_:
	ld a, [rSTAT]
	and STATF_LCD
	jr nz, WaitNextHBlank_
	ret

WaitNextHBlank:
	rst $38

; Hardware interrupts
SECTION "vblank", ROM0 [$40]
	reti

INCBIN "baserom.gbc", $41, $48 - $41

SECTION "hblank", ROM0 [$48]
	reti

INCBIN "baserom.gbc", $49, $50 - $49

SECTION "timer",  ROM0 [$50]
	reti

INCBIN "baserom.gbc", $51, $58 - $51

SECTION "serial", ROM0 [$58]
	reti

INCBIN "baserom.gbc", $59, $60 - $59

SECTION "joypad", ROM0 [$60]
	reti

SECTION "Home", ROM0 [$61]

INCBIN "baserom.gbc", $61, $68 - $61

; Waits until the VBlank period is entered.
WaitVBlank:
	ld a, [rLY]
	cp SCRN_Y + 1
	jr c, WaitVBlank
	ret

UpdateFrameCounter:
	ld a, [hPaused]
	and a
	ret nz
	ld hl, hFrameCounter
	inc [hl]
	ret

ResetFrameCounter:
	sub a
	ld [hFrameCounter], a
	ret

LoadCGBPalettesHome:
	ld a, Bank(LoadCGBPalettes)
	ld [MBC5RomBank], a
	jp LoadCGBPalettes

; The Warner Bros. Background banner graphics are only stored in ROM
; with the top-left quadrant. Since the other three quadrants are symmetric,
; this code unpacks the tiledata as such.
LoadWarnerBrosBannerQuadrants:
	push hl
	ld bc, $8830
	ld de, $8940
.asm_8b
	ld l, $09
.asm_8d
	ld a, [bc]
	inc bc
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	add a
	rr h
	ld a, h
	ld [de], a
	inc de
	ld a, c
	and $0f
	jr nz, .asm_8d
	ld a, e
	sub $20
	ld e, a
	ld a, d
	sbc 0
	ld d, a
	dec l
	jr nz, .asm_8d
	ld a, c
	add $90
	ld c, a
	ld a, b
	adc $00
	ld b, a
	ld a, e
	add $b0
	ld e, a
	ld a, d
	adc $01
	ld d, a
	ld a, b
	cp $90
	jr nz, .asm_8b
	ld bc, $8830
	ld de, $96de
	ld h, $07
.asm_d7
	ld l, $12
.asm_d9
	ld a, [bc]
	inc bc
	ld [de], a
	inc de
	ld a, [bc]
	inc bc
	ld [de], a
	dec de
	dec de
	dec de
	ld a, c
	and $0f
	jr nz, .asm_d9
	ld a, e
	add $20
	ld e, a
	ld a, d
	adc $00
	ld d, a
	dec l
	jr nz, .asm_d9
	ld a, e
	sub $40
	ld e, a
	ld a, d
	sbc $02
	ld d, a
	dec h
	jr nz, .asm_d7
	pop hl
	ret

SECTION "Entry", ROM0 [$100]

Func_100:
	nop
	jp Start


SECTION "Header", ROM0 [$104]

	; The header is generated by rgbfix.
	; The space here is allocated to prevent code from being overwritten.
	ds $150 - $104

SECTION "Main", ROM0

Start:
	ld [hGameBoyColorDetection], a
Start_:
	di
	ld sp, wStack
	ld a, Bank(ResetInitialData)
	ld [MBC5RomBank], a
	call ResetInitialData
	call ResetPlayerData
	call Func_3e31
	call SetInitialScreen
	jp InitNextScreen

INCBIN "baserom.gbc", $16a, $4f8 - $16a

InitInfogramesCopyrightScreen:
	call Func_fb4
	call Func_3dce
	call ResetFrameCounter
	sub a
	ld [rSCY], a
	ld [rSCX], a
	ld hl, InfogramesCopyrightScreenGBCPalettes
	call LoadCGBPalettesHome
	ld hl, vBGMap
	ld bc, $400
	call Func_10e9
	ld a, LCDCF_ON | LCDCF_WIN9C00 | LCDCF_WINOFF | LCDCF_BG8800 | LCDCF_BG9800 | LCDCF_OBJ16 | LCDCF_OBJOFF | LCDCF_BGON
	ld [rLCDC], a
.delayFrame
	call WaitVBlank
	call TryInitNextScreenHome
	call UpdateFrameCounter
	sub a
.delayNextVBlank
	dec a
	jr nz, .delayNextVBlank
	ld a, [hFrameCounter]
	and a
	jr nz, .delayFrame
	call Func_3ddc
	jr .delayFrame

InitWarnerBrosCopyrightScreen:
	call LoadWarnerBrosBannerQuadrants
	call Func_3e51
	call Func_3bb4
	call WriteDMACodeToHRAM
	call Func_3dce
	sub a
	ld [rSCY], a
	ld [rSCX], a
	ld hl, WarnerBrosCopyrightScreenGBCPalettes
	call LoadCGBPalettesHome
	ld a, LCDCF_ON | LCDCF_WIN9C00 | LCDCF_WINOFF | LCDCF_BG8800 | LCDCF_BG9800 | LCDCF_OBJ16 | LCDCF_OBJON | LCDCF_BGON
	ld [rLCDC], a
.asm_54e
	call TickMusicEngineHome
	call Func_3a82
	call WaitVBlank
	ld a, [$deee]
	cp $c5
	jr nc, .asm_56c
	ld a, $05
	ld [MBC5RomBank], a
	ld hl, $7861
	ld bc, $5c39
	call Func_3ca6
.asm_56c
	call ClearOAMBufferHome
	call TryInitNextScreenHome
	ld a, %10010000
	ld [rOBP0], a
	ld a, [$def2]
	and a
	jr nz, .asm_54e
	ld hl, $def6
	dec [hl]
	jr nz, .asm_54e
	call Func_3ddc
	jr .asm_54e

INCBIN "baserom.gbc", $587, $5ca - $587

Func_5ca:
	call LoadWarnerBrosBannerQuadrants
	call Func_3e51
	call WriteDMACodeToHRAM
	call Func_3dce
	call Func_3c72
	ld hl, $c502
	ld a, [hli]
	ld h, [hl]
	ld l, a
	call Func_3a4d
	sub a
	ld [rSCY], a
	ld [rSCX], a
	ld hl, WarnerBrosCopyrightScreenGBCPalettes
	call LoadCGBPalettesHome
	call Func_d67
	ld a, LCDCF_ON | LCDCF_WIN9C00 | LCDCF_WINOFF | LCDCF_BG8800 | LCDCF_BG9800 | LCDCF_OBJ16 | LCDCF_OBJON | LCDCF_BGON
	ld [rLCDC], a
Func_5f4:
	call TickMusicEngineHome
	call WaitVBlank
	ld a, $05
	ld [MBC5RomBank], a
	ld hl, $731c
	ld bc, $0
	call Func_3ca6
	call ClearOAMBufferHome
	call TryInitNextScreenHome
	call ReadJoyPad_Home
	ld a, [wLanguageSetting]
	swap a
	add 55
	ld b, a
	ld c, $14
	ld hl, $6db3
	ld a, $05
	ld [MBC5RomBank], a
	call Func_3ca6
	ld a, [$defc]
	and a
	jp nz, Func_5f4
	ld hl, wLanguageSetting
	ld a, [wNewKeys]
	bit PADB_SELECT, a
	jr nz, .moveCursorDown
	add a ; check if down pressed (PADF_DOWN)
	jr nc, .checkUpPressed
.moveCursorDown
	inc [hl]
	jr .resolveCursor
.checkUpPressed
	add a
	jr nc, .ok
	dec [hl]
.resolveCursor
	ld b, 3 ; num languages
	ld a, [hl]
	cp $ff
	jr nz, .checkMax
	dec b
	ld [hl], b
	jr .redraw
.checkMax
	cp b
	jr c, .redraw
	ld [hl], $00
.redraw
	ld a, $07
	call Func_3e1b
.ok
	ld a, [wNewKeys]
	and PADF_START | PADF_A
	jp z, Func_5f4
	ld a, $08
	call Func_3e1b
	call Func_3ddc
	jp Func_5f4

INCBIN "baserom.gbc", $669, $d67 - $669

Func_d67:
	ld hl, vBGMap
	ld bc, $400
.asm_d6d
	ld a, $7f
	ld [hli], a
	dec bc
	ld a, c
	or b
	jr nz, .asm_d6d
	ld hl, $9841
	ld bc, $e
	ld a, $83
	ld d, $0e
.asm_d7f
	ld e, $12
.asm_d81
	ld [hli], a
	inc a
	dec e
	jr nz, .asm_d81
	add hl, bc
	dec d
	jr nz, .asm_d7f
	ret

INCBIN "baserom.gbc", $d8b, $e5c - $d8b

InitStudioCreditsScreen:
	ld bc, wInCreditsScene
	ld a, $ff
	ld [bc], a
	inc c
	ld a, $01
	ld [bc], a
	inc c
	sub a
	ld [bc], a
	inc c
	ld a, $56
	ld [bc], a
	inc c
	ld a, $76
	ld [bc], a
	jr asm_e77
InitStudioScreen:
	sub a
	ld [wInCreditsScene], a
asm_e77:
	push hl
	ld hl, StudioScreenData
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	jr nz, .load
	ld hl, StudioScreenData_GBC
.load
	call LoadData
	call Func_3e51
	call Func_fb4
	ld hl, StudioScreenGBCPalettes
	call LoadCGBPalettesHome
	pop hl
	call Func_2b6d
	ld bc, $ff9c
	ld a, [bc]
	sub $08
	ld [bc], a
	inc c
	ld a, [bc]
	sbc 0
	ld [bc], a
	call Func_1965
	call Func_39f1
	call Func_2342
	call Func_3335
	call Func_392e
	call Func_2d73
	call Func_3dce
	call Func_3c72
	call WriteDMACodeToHRAM
	call ResetFrameCounter
	call Func_31e1
	sub a
	ld [$de84], a
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	jr nz, .asm_ed7
	ld hl, $9b00
	ld bc, $100
	call Func_10e9
.asm_ed7
	ld hl, $9b00
.asm_eda
	ld a, [hl]
	sub $b8
	ld [hli], a
	ld a, l
	and a
	jr nz, .asm_eda
	ld a, 144
	ld [rWY], a
	ld a, 165
	ld [rWX], a
	ld a, [wInCreditsScene]
	and a
	jr z, .initLCDC
	ld hl, Data_1b77d
	call LoadData
.initLCDC
	ld a, LCDCF_ON | LCDCF_WIN9C00 | LCDCF_WINON | LCDCF_BG8800 | LCDCF_BG9800 | LCDCF_OBJ16 | LCDCF_OBJON | LCDCF_BGON
	ld [rLCDC], a
.mainLoop:
	call ClearOAMBufferHome
	ld a, [wInCreditsScene]
	and a
	jr nz, .tryInitNextScreen
	call ReadJoyPad_Home
	call TryTogglePause
.tryInitNextScreen
	call TryInitNextScreenHome
.waitPastCeiling
	ld a, [rLY]
	cp 31
	jr nz, .waitPastCeiling
	call WaitHBlankStart
	ld a, [hCameraXOffset]
	ld [rSCX], a
	ld a, [hCameraYOffset]
	ld [rSCY], a
	call TickMusicEngineHome
	ld a, [wInCreditsScene]
	and a
	jr z, .asm_f49
	ld a, Bank(Func_f610)
	ld [MBC5RomBank], a
	call Func_f610
	ld a, [hFrameCounter]
	rra
	jr c, .asm_f55
	ld hl, $dde3
	ld a, [hli]
	ld [$ffa4], a
	ld a, [hFrameCounter]
	and $03
	jr nz, .asm_f55
	inc [hl]
	jr nz, .asm_f55
	dec l
	ld a, [hl]
	cpl
	inc a
	ld [hl], a
	jr .asm_f55
.asm_f49
	call HandlePlayerInput
	call Func_1940
	call $235e
	call PrepareCameraUpdate
.asm_f55
	call Func_2a84
	ld a, [wInCreditsScene]
	and a
	jr nz, .asm_f61
	call Func_2c9f
.asm_f61
	call Func_3939
	call Func_3252
.waitFloor
	ld a, [rLY]
	cp 111
	jr nz, .waitFloor
	call WaitHBlankStart
	ld hl, hCameraXOffset + 1
	ld a, [hld]
	ld b, a
	ld a, [hl]
	srl b
	rra
	srl b
	rra
	add [hl]
	ld [rSCX], a
	ld a, 112
	ld [rSCY], a
.waitSecondaryFloor
	ld a, [rLY]
	cp 118
	jr nz, .waitSecondaryFloor
	call WaitHBlankStart
	ld hl, hCameraXOffset + 1
	ld a, [hld]
	ld b, a
	ld a, [hl]
	srl b
	rra
	add [hl]
	ld [rSCX], a
	call $2e27
	ld a, 192
	ld [rSCY], a
	ld hl, hCameraXOffset + 1
	ld a, [hld]
	ld b, a
	ld a, [hl]
	srl b
	rra
	srl b
	rra
	add [hl]
	ld [rSCX], a
	call UpdateFrameCounter
	jp .mainLoop

Func_fb4:
	ld bc, $da00
	ld de, $da80
.asm_fba
	ld a, [bc]
	ld [$ff8a], a
	ld a, [de]
	ld [bc], a
	inc c
	ld a, [$ff8a]
	ld [de], a
	inc e
	jr nz, .asm_fba
	ld bc, $d900
	ld de, $d980
.asm_fcc
	ld a, [bc]
	ld [$ff8a], a
	ld a, [de]
	ld [bc], a
	inc c
	ld a, [$ff8a]
	ld [de], a
	inc e
	jr nz, .asm_fcc
	ret

INCBIN "baserom.gbc", $fd9, $10e9 - $fd9

Func_10e9:
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ret nz
	ld d, $d9
.loop
	sub a
	ld [rVBK], a
	ld e, [hl]
	ld a, 1
	ld [rVBK], a
	ld a, [de]
	ld [hli], a
	dec bc
	ld a, c
	or b
	jr nz, .loop
	sub a
	ld [rVBK], a
	ret

INCBIN "baserom.gbc", $1103, $1940 - $1103

Func_1940:
	ld a, Bank(Func_17929)
	ld [MBC5RomBank], a
	jp Func_17929

INCBIN "baserom.gbc", $1948, $1965 - $1948

Func_1965:
	ld c, $c2
	ld b, $06
	sub a
.asm_196a
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .asm_196a
	push hl
	ld b, $04
.asm_1972
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .asm_1972
	sub a
	ld [$ff00+c], a
	inc c
	pop hl
	ld b, $04
.asm_197e
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .asm_197e
	sub a
	ld [$ff00+c], a
	inc c
	ld [$ff00+c], a
	ret

HandlePlayerInput:
	ld a, [hPaused]
	and a
	ret nz
	ld hl, $de84
	ld a, [hl]
	and a
	jr z, .asm_1996
	dec [hl]
	ret
.asm_1996
	ld hl, $ffad
	ld a, [hli]
	ld b, a
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld d, a
	ld a, [wHeldKeys]
	ld e, a
	ld a, [$ffb5]
	and a
	jp nz, $1a37
	bit 2, b
	jp nz, Func_1a73
	ld a, [hl]
	add $b8
	ld l, a
	ld a, $19
	adc $00
	ld h, a
	jp hl
	jp Func_1afd

INCBIN "baserom.gbc", $19bb, $19e5 - $19bb

Func_19e5:
	bit 1, b
	jr nz, asm_19f2
Func_19e9:
	ld hl, $ffad
	ld a, b
	ld [hli], a
	ld a, c
	ld [hli], a
	ld [hl], d
	ret
asm_19f2:
	ld hl, $ffb9
	ld a, [hl]
	inc [hl]
	and a
	jr nz, .asm_1a2d
	bit 4, b
	jr z, .asm_1a15
	ld a, [$ffb0]
	and a
	jr nz, .asm_1a15
	bit 4, d
	jr nz, .asm_1a15
	ld a, $d0
	ld [$ffc6], a
	res 4, b
	ld d, $20
	ld hl, $2dbd
	call Func_2d62
.asm_1a15
	ld a, $13
	call Func_3e1b
	ld a, [hCurHealth]
	sub $01
	jr nc, .asm_1a29
	call Func_1ae2
	set 2, b
	ld d, $00
	jr .asm_1a35
.asm_1a29
	ld [hCurHealth], a
	jr .asm_1a35
.asm_1a2d
	cp $78
	jr c, .asm_1a35
	sub a
	ld [hl], a
	res 1, b
.asm_1a35
	jr Func_19e9

INCBIN "baserom.gbc", $1a37, $1a73 - $1a37

Func_1a73:
	sub a
	ld [$ffb9], a
	ld [$ffb7], a
	bit 4, b
	jr nz, .asm_1a84
	ld hl, $2dbd
	call Func_2d62
	jr .asm_1adf
.asm_1a84
	push bc
	push de
	ld a, [hPlayerXPos]
	sub $0a
	bit 5, b
	jr z, .asm_1a90
	add $0c
.asm_1a90
	ld c, a
	ld a, [hPlayerYPos]
	sub $18
	ld b, a
	ld hl, $1af3
	call Func_3c98
	ld hl, $2db9
	call Func_2d62
	ld hl, $ffb8
	ld a, [hFrameCounter]
	rra
	jr nc, .asm_1aab
	inc [hl]
.asm_1aab
	ld a, [hl]
	cp $69
	jr z, .asm_1abd
	cp $01
	jr nz, .asm_1add
	inc [hl]
	ld hl, $4083
	call Func_3e71
	jr .asm_1add
.asm_1abd
	inc [hl]
	ld a, [$deff]
	dec a
	ld [$deff], a
	ld a, [hMaxHealth]
	ld [hCurHealth], a
	ld a, [hNumLives]
	and a
	jr nz, .asm_1ad5
	ld a, $4b
	ld [$deff], a
	jr .asm_1ada
.asm_1ad5
	sub $01
	daa
	ld [hNumLives], a
.asm_1ada
	call Func_3ddc
.asm_1add
	pop de
	pop bc
.asm_1adf
	jp Func_19e9


Func_1ae2:
	ld a, [$ffad]
	bit 2, a
	ret nz
	set 2, a
	ld [$ffad], a
	sub a
	ld [hCurHealth], a
	ld [$ffb0], a
	jp Func_2326

INCBIN "baserom.gbc", $1af3, $1afd - $1af3

Func_1afd:
	bit 4, d
	jp nz, Func_1d0e
	ld a, [$ffb6]
	and a
	jr z, .asm_1b1d
	dec a
	ld [$ffb6], a
	jr nz, .asm_1b0e
	res 2, d
.asm_1b0e
	ld a, e
	and $30
	jr nz, .asm_1b1d
	bit 5, b
	jr z, .asm_1b1b
	set 5, e
	jr .asm_1b1d
.asm_1b1b
	set 4, e
.asm_1b1d
	call Func_1b2f
	call Func_1b46
	call Func_1bdc
	call Func_1c9f
	call Func_1cdc
	jp Func_19e5

Func_1b2f:
	ld a, [$ffb4]
	and a
	ret nz
	bit 7, e
	jr z, .asm_1b43
	bit 4, b
	jr z, .asm_1b43
	ld d, $01
	ld hl, $2d89
	jp Func_2d62
.asm_1b43
	res 0, d
	ret

Func_1b46:
	ld a, [$ffe8]
	and a
	jr nz, .asm_1ba3
	ld a, [$ffc6]
	bit 7, a
	jr nz, .asm_1b55
	cp $38
	jr nc, .asm_1b69
.asm_1b55
	bit 5, e
	jr z, .asm_1b5f
	set 5, b
	ld a, $fe
	jr .asm_1b71
.asm_1b5f
	bit 4, e
	jr z, .asm_1b69
	res 5, b
	ld a, $02
	jr .asm_1b71
.asm_1b69
	sub a
	ld [$ffc4], a
.asm_1b6c
	res 2, d
	res 3, d
	ret
.asm_1b71
	ld [$ffc4], a
	bit 4, b
	jr z, .asm_1b6c
	ld a, [$ffb4]
	and a
	jr nz, .asm_1b69
	bit 0, d
	jr nz, .asm_1b69
	bit 3, b
	jr nz, .asm_1b98
	bit 2, d
	ret nz
	ld d, $04
	ld hl, $2d8d
	ld a, [$ffb6]
	and a
	jp z, Func_2d62
	ld hl, $2d91
	jp Func_2d62
.asm_1b98
	bit 3, d
	ret nz
	ld d, $08
	ld hl, $2d95
	jp Func_2d62
.asm_1ba3
	res 2, d
	res 3, d
	sub a
	bit 5, e
	jr z, .asm_1bb2
	set 5, b
	ld a, $fe
	jr .asm_1bba
.asm_1bb2
	bit 4, e
	jr z, .asm_1bba
	res 5, b
	ld a, $02
.asm_1bba
	ld [$ffc4], a
	bit 4, b
	ret z
	ld a, [$ffb4]
	and a
	ret nz
	bit 0, d
	ret nz
	ld hl, $78ec
	ld a, [hFrameCounter]
	bit 5, a
	jr z, .asm_1bd2
	ld hl, $78f0
.asm_1bd2
	ld a, l
	ld [$ffd6], a
	ld a, h
	ld [$ffd7], a
	sub a
	ld [$ffd5], a
	ret

Func_1bdc:
	ld hl, $ffb2
	ld a, [hli]
	and a
	jr z, .asm_1bfb
	dec l
	dec [hl]
	inc hl
	jr nz, .asm_1bf3
	bit 1, e
	jr z, .asm_1bf3
	ld a, [hNumCarrots]
	and a
	jr z, .asm_1bf3
	ld [hl], $01
.asm_1bf3
	ld a, $d0
	ld [$ffc6], a
	res 4, b
	jr .asm_1c58
.asm_1bfb
	bit 1, e
	jr z, .asm_1c49
	ld a, [hl]
	and a
	jr z, .asm_1c30
	inc [hl]
	ld a, [hl]
	cp $1c
	jr nz, .asm_1c0e
	ld a, $0a
	call Func_3e1b
.asm_1c0e
	ld a, [hNumCarrots]
	add $1c
	add $10
	cp [hl]
	jr nc, .asm_1c1b
	ld [hl], $00
	jr .asm_1c30
.asm_1c1b
	ld a, [hl]
	cp $1c
	jr c, .asm_1c30
	jr nz, .asm_1c28
	ld hl, $2da5
	call Func_2d62
.asm_1c28
	ld a, $f0
	ld [$ffc6], a
	res 4, b
	jr .asm_1c51
.asm_1c30
	bit 6, b
	jr nz, .asm_1c4d
	bit 4, b
	jr z, .asm_1c58
	ld a, [$ffb4]
	and a
	ret nz
	ld a, $06
	ld [$ffb2], a
	ld a, $0b
	call Func_3e1b
	set 6, b
	jr Func_1bdc
.asm_1c49
	res 6, b
	ld [hl], $00
.asm_1c4d
	bit 4, b
	jr z, .asm_1c58
.asm_1c51
	res 5, d
	res 6, d
	res 7, d
	ret
.asm_1c58
	ld a, [$ffb4]
	and a
	ret nz
	ld a, [$ffc6]
	add a
	jr c, .asm_1c94
	bit 1, e
	jr z, .asm_1c7b
	ld a, [$ffb3]
	and a
	jr nz, .asm_1c7b
	bit 7, b
	jr z, .asm_1c7b
	set 6, b
	bit 7, d
	ret nz
	ld d, $80
	ld hl, $2dc1
	jp Func_2d62
.asm_1c7b
	ld a, [$ffc6]
	cp $38
	jr c, .asm_1c89
	ld d, $00
	ld hl, $2db5
	jp Func_2d62
.asm_1c89
	bit 6, d
	ret nz
	ld d, $40
	ld hl, $2da1
	jp Func_2d62
.asm_1c94
	bit 5, d
	ret nz
	ld d, $20
	ld hl, $2d9d
	jp Func_2d62

Func_1c9f:
	ld hl, $ffb4
	ld a, [hl]
	and a
	jr z, .asm_1cac
	dec [hl]
	ld d, $00
	sub a
	ld [$ffb3], a
.asm_1cac
	bit 0, e
	jr nz, .asm_1cb3
	res 0, c
	ret
.asm_1cb3
	bit 0, c
	ret nz
	ld a, [hl]
	and a
	ret nz
	bit 0, d
	ret nz
	bit 7, d
	ret nz
	ld a, [$ffc6]
	bit 7, a
	jr nz, .asm_1cc8
	cp $38
	ret nc
.asm_1cc8
	set 0, c
	ld d, $00
	sub a
	ld [$ffb3], a
	ld [hl], $0e
	ld a, $01
	call Func_3e1b
	ld hl, $2da9
	jp Func_2d62

Func_1cdc:
	ld a, [$ffb4]
	and a
	ret nz
	ld a, d
	and $fd
	ret nz
	bit 4, b
	jr z, .asm_1d0b
	ld a, [wNewKeys]
	bit PADB_SELECT, a
	jr z, .asm_1d00
	ld a, [hForcedSideScrollSpeed]
	and a
	jr nz, .asm_1d00
	ld a, $3c
	ld [$ffb1], a
	ld d, $10
	ld hl, $2d99
	jp Func_2d62
.asm_1d00
	bit 1, d
	ret nz
	ld d, $02
	ld hl, $2d85
	jp Func_2d62
.asm_1d0b
	res 1, d
	ret

Func_1d0e:
	call Func_2329
	ld hl, $ffb1
	dec [hl]
	jr nz, .asm_1d1d
	ld d, $02
	ld a, b
	xor $80
	ld b, a
.asm_1d1d
	jp Func_19e5

INCBIN "baserom.gbc", $1d20, $2326 - $1d20

Func_2326:
	sub a
	ld [$ffaf], a
Func_2329:
	sub a
	ld [$ffc5], a
	sub a
	ld [$ffc2], a
	ld [$ffc3], a
	ld [$ffc4], a
	ld [$ffc6], a
	ld [$ffb2], a
	ld [$ffb3], a
	ld [$ffb4], a
	ld [$ffb6], a
	ld [$ffd1], a
	ld [$ffd2], a
	ret

Func_2342:
	ld a, $06
	ld [MBC5RomBank], a
	ld a, [hli]
	ld [$ffaa], a
	ld a, [hli]
	ld [$ffab], a
	ld c, $ac
	ld b, $14
	sub a
.asm_2352
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .asm_2352
	ld a, [$ffad]
	set 4, a
	ld [$ffad], a
	ret

INCBIN "baserom.gbc", $235e, $29e9 - $235e

PrepareCameraUpdate:
	ld a, [hPaused]
	and a
	ret nz
	ld a, [$de84]
	and a
	ret nz
	ld a, [hForcedSideScrollSpeed]
	add a
	jr z, .asm_29fb
	jr c, .asm_2a32
	jr .asm_2a57
.asm_29fb
	ld bc, $4fc
	ld a, [hCameraXOffset]
	ld d, a
	ld a, [hPlayerXPos]
	sub d
	sub 76 ; x pixel position for when the camera starts scrolling horizontally
	bit 7, a
	jr nz, .asm_2a10
	cp b
	jr c, .asm_2a14
	ld a, b
	jr .asm_2a14
.asm_2a10
	cp c
	jr nc, .asm_2a14
	ld a, c
.asm_2a14
	ld [$ffa4], a
	ld bc, $4fc
	ld a, [hCameraYOffset]
	ld d, a
	ld a, [hPlayerYPos]
	sub d
	sub 88 ; y pixel position for when the camera starts scrolling vertically
	bit 7, a
	jr nz, .asm_2a2b
	cp b
	jr c, .asm_2a2f
	ld a, b
	jr .asm_2a2f
.asm_2a2b
	cp c
	jr nc, .asm_2a2f
	ld a, c
.asm_2a2f
	ld [$ffa5], a
	ret
.asm_2a32
	sub a
	ld [$ffa5], a
	ld a, [$ffad]
	bit 2, a
	ret nz
	ld a, [hCameraXOffset]
	and a
	jr nz, .asm_2a43
	ld a, [hCameraXOffset + 1]
	and a
	ret z
.asm_2a43
	ld a, [hForcedSideScrollSpeed]
	cp $fe
	jr nz, .asm_2a4e
	ld a, $ff
	ld [$ffa4], a
	ret
.asm_2a4e
	ld a, [hFrameCounter]
	rra
	ret c
	ld a, [hForcedSideScrollSpeed]
	ld [$ffa4], a
	ret
.asm_2a57
	sub a
	ld [$ffa5], a
	ld a, [$ffad]
	bit 2, a
	ret nz
	ld a, [hCameraXOffset]
	add $b1
	ld c, a
	ld a, [hCameraXOffset + 1]
	adc $00
	ld b, a
	ld a, [$ff98]
	sub c
	ld a, [$ff99]
	sbc b
	ret c
	ld a, [hForcedSideScrollSpeed]
	cp $01
	jr z, .asm_2a7b
	srl a
	ld [$ffa4], a
	ret
.asm_2a7b
	ld a, [hFrameCounter]
	rra
	ret c
	ld a, [hForcedSideScrollSpeed]
	ld [$ffa4], a
	ret

Func_2a84:
	ld a, Bank(Func_17643)
	ld [MBC5RomBank], a
	jp Func_17643

; Prepares a metatile to be drawn on screen.
; Input: bc = metatile x pixel offset
;        de = metatile y pixel offset
;
; Returns: hl = metatile source address
;          de = bg map destination address
;          b  = 0 if metatile should be drawn, $ff if it shouldn't be drawn
PrepareDrawMetatile:
	bit 7, b
	jr nz, .dontDrawMetatile ; exit if metatile has negative x offset
	bit 7, d
	jr nz, .dontDrawMetatile ; exit if metatile has negative y offset
	ld hl, hLevelPixelWidth
	ld a, [hli]
	sub c
	ld a, [hli]
	sbc b
	jr c, .dontDrawMetatile ; exit if metatile is outside horizontal boundaries
	ld a, [hli]
	sub e
	ld a, [hli]
	sbc d
	jr c, .dontDrawMetatile ; exit if metatile is outside vertical boundaries
	ld h, b
	ld l, c
	add hl, hl
	add hl, hl
	ld b, h ; b = metatile horizontal offset
	ld h, d
	ld l, e
	add hl, hl
	add hl, hl
	ld l, h ; l = metatile vertical offset
	ld h, (wMetatileRowPointers >> 8)
	sla l
	ld a, [hli]
	ld h, [hl]
	sla b
	add b
	ld l, a
	jr nc, .asm_2aba
	inc h
.asm_2aba
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, e
	and $30
	rrca
	rrca
	add l
	ld l, a
	ld a, c
	and $30
	swap a
	add l
	ld l, a
	ld l, [hl]
	ld h, (wMetatiles >> 10)
	add hl, hl
	add hl, hl
	ld d, (_SCRN0 >> 10)
	ld a, e
	and $f0
	add a
	rl d
	ld e, a
	ld a, c
	and $f0
	swap a
	add e
	add a
	rl d
	ld e, a
	ld b, 0
	ret
.dontDrawMetatile
	ld b, $ff
	ret

DrawMetatile_HBlank:
	ld a, [rSTAT]
	and STATF_LCD
	jr z, DrawMetatile_HBlank ; wait for current HBlank to end
.waitHBlank
	ld a, [rSTAT]
	and STATF_LCD
	jr nz, .waitHBlank
DrawMetatile:
	ld a, b
	and a
	ret nz
	; load the 4 tiles defined by the metatile
	ld a, [hli]
	ld [de], a
	inc e
	ld a, [hli]
	ld [de], a
	ld a, e
	add $1f ; jump to the lower-left tile in the metatile
	ld e, a
	ld a, [hli]
	ld [de], a
	inc e
	ld a, [hl]
	ld [de], a
	ret

; Draws the metatile's GBC tile attributes during HBlank.
; Input: hl = last tile in metatile
;        de = destination bg address for last tile in metatile
;        b  = 0 if metatile should be drawn, $ff if it should be skipped
DrawMetatileGBCAttributes_HBlank:
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ret nz
.waitCurrentHBlankFinish
	ld a, [rSTAT]
	and STATF_LCD
	jr z, .waitCurrentHBlankFinish
.waitHBlankStart
	ld a, [rSTAT]
	and STATF_LCD
	jr nz, .waitHBlankStart
	ld a, b
	and a
	ret nz
	ld b, (wGBCTileAttributes >> 8)
	ld a, 1
	ld [rVBK], a
	ld a, [hld]
	ld c, a
	ld a, [bc]
	ld [de], a
	dec e
	ld a, [hld]
	ld c, a
	ld a, [bc]
	ld [de], a
.waitCurrentHBlankFinish2
	ld a, [rSTAT]
	and STATF_LCD
	jr z, .waitCurrentHBlankFinish2
.waitHBlankStart2
	ld a, [rSTAT]
	and STATF_LCD
	jr nz, .waitHBlankStart2
	ld a, e
	sub $1f ; jump up to previous row in bg for metatile
	ld e, a
	ld a, [hld]
	ld c, a
	ld a, [bc]
	ld [de], a
	dec e
	ld c, [hl]
	ld a, [bc]
	ld [de], a
	sub a
	ld [rVBK], a
	ret

; Draws the metatile's GBC tile attributes.
; Input: hl = last tile in metatile
;        de = destination bg address for last tile in metatile
;        b  = 0 if metatile should be drawn, $ff if it should be skipped
DrawMetatileGBCAttributes:
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ret nz
	ld a, b
	and a
	ret nz
	ld b, (wGBCTileAttributes >> 8)
	ld a, 1
	ld [rVBK], a
	ld a, [hld]
	ld c, a
	ld a, [bc]
	ld [de], a
	dec e
	ld a, [hld]
	ld c, a
	ld a, [bc]
	ld [de], a
	ld a, e
	sub $1f ; jump up to previous bg row for metatile
	ld e, a
	ld a, [hld]
	ld c, a
	ld a, [bc]
	ld [de], a
	dec e
	ld c, [hl]
	ld a, [bc]
	ld [de], a
	sub a
	ld [rVBK], a
	ret

Func_2b6d:
	ld a, $06
	ld [MBC5RomBank], a
	ld c, (hCameraXOffset & $ff)
	ld b, $04
.asm_2b76
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .asm_2b76
	ld a, [hCameraXOffset]
	ld [rSCX], a
	ld a, [hCameraYOffset]
	ld [rSCY], a
	sub a
	ld [$ff00+c], a
	inc c
	ld [$ff00+c], a
	inc c
	push hl
	ld hl, wLevelMap
	ld b, 2
.initLevelPixelDimensions
	ld a, [hli]
	sub $01
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	sbc 0
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .initLevelPixelDimensions
	ld a, [hli]
	ld e, a
	ld d, [hl]
	ld hl, wLevelMap + 6
	ld bc, wMetatileRowPointers
.asm_2ba5
	ld a, l
	ld [bc], a
	inc c
	ld a, h
	ld [bc], a
	add hl, de
	inc c
	jr nz, .asm_2ba5
	ld c, $95
	sub a
	ld [$ff00+c], a
	inc c
	ld hl, $c600
	ld de, hScore
	ld a, e
	ld [$ff00+c], a
	inc c
	ld a, d
	ld [$ff00+c], a
	inc c
	call Func_2bdf
	sub a
	ld [$ff00+c], a
	inc c
	ld [$ff00+c], a
	inc c
	call Func_2bdf
	ld a, e
	ld [$ff00+c], a
	inc c
	ld a, d
	ld [$ff00+c], a
	ld hl, $ff9c
	ld a, [hl]
	add $08
	ld [hli], a
	ld a, [hl]
	adc 0
	ld [hl], a
	call DrawWholeScreenMetatiles
	pop hl
	ret

Func_2bdf:
	ld a, [hli]
	add $10
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	adc $00
	ld [$ff00+c], a
	inc c
	ret

DrawWholeScreenMetatiles:
	ld hl, hCameraXOffset
	ld a, [hli]
	sub $10
	ld c, a
	ld a, [hli]
	sbc 0
	ld b, a
	ld a, [hli]
	sub $10
	ld e, a
	ld a, [hli]
	sbc 0
	ld d, a
	ld h, $10
.rowLoop
	ld l, $10
.metatileLoop
	push hl
	push bc
	push de
	call PrepareDrawMetatile
	call DrawMetatile
	call DrawMetatileGBCAttributes
	pop de
	pop bc
	ld hl, $10
	add hl, bc
	ld b, h
	ld c, l
	pop hl
	dec l
	jr nz, .metatileLoop
	push hl
	ld hl, $ff00
	add hl, bc
	ld b, h
	ld c, l
	ld hl, $10
	add hl, de
	ld d, h
	ld e, l
	pop hl
	dec h
	jr nz, .rowLoop
	ret

INCBIN "baserom.gbc", $2c2b, $2c9f - $2c2b

Func_2c9f:
	ld a, [hPaused]
	and a
	ret nz
	ld a, $0e
	ld [MBC5RomBank], a
	ld hl, $ffd7
	ld a, [hld]
	ld b, a
	ld a, [hld]
	ld c, a
	inc [hl]
	ld a, [bc]
	cp [hl]
	jr nz, .asm_2cc8
	sub a
	ld [hli], a
	inc bc
	inc bc
	inc bc
	inc bc
	ld a, [bc]
	and a
	jr nz, .asm_2cc5
	inc bc
	ld a, [bc]
	inc bc
	ld d, a
	ld a, [bc]
	ld b, a
	ld c, d
.asm_2cc5
	ld a, c
	ld [hli], a
	ld [hl], b
.asm_2cc8
	ld a, [hFrameCounter]
	rra
	jr c, .asm_2cd9
	ld hl, $ffd8
	inc bc
	ld a, [bc]
	inc bc
	ld [hli], a
	ld a, [bc]
	inc bc
	ld [hli], a
	ld a, [bc]
	ld [hl], a
.asm_2cd9
	ld a, [hActiveSprites]
	ld c, a
	ld b, $df
	ld hl, $ffd8
	sub a
	ld [$ff8a], a
	ld a, [hli]
	ld [MBC5RomBank], a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	dec hl
	ld a, [hli]
	ld [$ff8b], a
	ld a, [hli]
	inc hl
	and $1f
	ld [$ff8c], a
	ld a, [hCameraXOffset]
	ld d, a
	ld a, [hPlayerXPos]
	sub d
	ld d, a
	ld a, [hCameraYOffset]
	ld e, a
	ld a, [hPlayerYPos]
	sub e
	ld e, a
	ld a, [$ffb9]
	and a
	jr z, .asm_2d0d
	bit 1, a
	jr nz, .asm_2d16
	ret
.asm_2d0d
	ld a, [$ffb7]
	cp $0c
	jr nc, .asm_2d16
	bit 1, a
	ret nz
.asm_2d16
	ld a, [$ffad]
	bit 5, a
	jr z, .asm_2d24
	ld a, [$ff8b]
	set 5, a
	ld [$ff8b], a
	jr .asm_2d42
.asm_2d24
	ld a, [hli]
	add e
	ld [bc], a
	inc c
	ld a, [hli]
	inc hl
	add d
	ld [bc], a
	inc c
	ld a, [$ff8a]
	ld [bc], a
	inc c
	add $02
	ld [$ff8a], a
	ld a, [$ff8b]
	ld [bc], a
	inc c
	ld a, [$ff8c]
	dec a
	ld [$ff8c], a
	jr nz, .asm_2d24
	jr .asm_2d5e
.asm_2d42
	ld a, [hli]
	add e
	ld [bc], a
	inc c
	inc hl
	ld a, [hli]
	add d
	ld [bc], a
	inc c
	ld a, [$ff8a]
	ld [bc], a
	inc c
	add $02
	ld [$ff8a], a
	ld a, [$ff8b]
	ld [bc], a
	inc c
	ld a, [$ff8c]
	dec a
	ld [$ff8c], a
	jr nz, .asm_2d42
.asm_2d5e
	ld a, c
	ld [hActiveSprites], a
	ret

Func_2d62:
	ld a, [$ffad]
	add a
	jr nc, .asm_2d69
	inc hl
	inc hl
.asm_2d69
	ld a, [hli]
	ld [$ffd6], a
	ld a, [hl]
	ld [$ffd7], a
	sub a
	ld [$ffd5], a
	ret

Func_2d73:
	ld hl, $2d85
	call Func_2d62
	ld hl, $ffd8
	ld a, $0d
	ld [hli], a
	ld a, $c1
	ld [hli], a
	ld [hl], $74
	ret

INCBIN "baserom.gbc", $2d85, $31e1 - $2d85

Func_31e1:
	ld a, $05
	ld [MBC5RomBank], a
	ld a, [hForcedSideScrollSpeed]
	ld hl, $722c
	ld bc, vBGWin
	and a
	jr z, .asm_31fe
	ld hl, $7268
	ld bc, $9ba0
	cp $fe
	jr nz, .asm_31fe
	ld hl, $72a4
.asm_31fe
	ld d, $03
.asm_3200
	ld e, $14
.asm_3202
	ld a, [hli]
	ld [bc], a
	inc c
	dec e
	jr nz, .asm_3202
	ld a, c
	add $0c
	ld c, a
	ld a, b
	adc $00
	ld b, a
	dec d
	jr nz, .asm_3200
	sub a
	ld [$ffec], a
	ld [hNumCarrots], a
	ld [hCarrotMeter], a
	ld [$fff2], a
	ld [$fff5], a
	ld [$fff6], a
	ld [$fff7], a
	ld [$fff8], a
	ld [$fff9], a
	ld [$fffa], a
	ld [$fffb], a
	ld [$fffc], a
	ld [$fffd], a
	ret

ResetPlayerData:
	ld a, [wDifficultySetting]
	ld bc, $505
	ld d, 4
	and a
	jr z, .setData
	ld bc, $404
	ld d, 3
.setData
	ld a, b
	ld [hCurHealth], a
	ld a, c
	ld [hMaxHealth], a
	ld a, d
	ld [hNumLives], a
	sub a
	ld [hScore], a
	ld [hScore + 1], a
	ret

INCBIN "baserom.gbc", $324e, $3252 - $324e

Func_3252:
	ld a, [hPaused]
	and a
	ret nz
	ld hl, $dd80
	ld a, [hli]
	ld [$ff8a], a
	ld a, $14
	ld [$ff8b], a
	ld a, $0c
	ld [MBC5RomBank], a
.asm_3265
	ld a, [$ff8a]
	and a
	jr z, .asm_32df
	dec a
	ld [$ff8a], a
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	ld a, [hCameraYOffset]
	ld e, a
	ld a, [bc]
	inc bc
	inc bc
	sub e
	ld e, a
	ld a, [hCameraXOffset]
	ld d, a
	ld a, [bc]
	inc bc
	inc bc
	sub d
	ld d, a
	ld a, [hli]
	push hl
	ld h, [hl]
	ld l, a
	dec hl
	ld a, [bc]
	and $20
	or [hl]
	inc hl
	ld [$ff8c], a
	ld a, [hli]
	inc hl
	and $1f
	ld [$ff8d], a
	ld a, [hActiveSprites]
	ld c, a
	ld b, $df
	ld a, [$ff8c]
	bit 5, a
	jr nz, .asm_32bc
.asm_329e
	ld a, [hli]
	add e
	ld [bc], a
	inc c
	ld a, [hli]
	inc hl
	add d
	ld [bc], a
	inc c
	ld a, [$ff8b]
	ld [bc], a
	inc c
	add $02
	ld [$ff8b], a
	ld a, [$ff8c]
	ld [bc], a
	inc c
	ld a, [$ff8d]
	dec a
	ld [$ff8d], a
	jr nz, .asm_329e
	jr .asm_32d8
.asm_32bc
	ld a, [hli]
	add e
	ld [bc], a
	inc c
	inc hl
	ld a, [hli]
	add d
	ld [bc], a
	inc c
	ld a, [$ff8b]
	ld [bc], a
	inc c
	add $02
	ld [$ff8b], a
	ld a, [$ff8c]
	ld [bc], a
	inc c
	ld a, [$ff8d]
	dec a
	ld [$ff8d], a
	jr nz, .asm_32bc
.asm_32d8
	pop hl
	inc hl
	ld a, c
	ld [hActiveSprites], a
	jr .asm_3265
.asm_32df
	ld bc, $dd80
	ld a, [hFrameCounter]
	rra
	jr c, .asm_32ea
	sub a
	ld [bc], a
	ret
.asm_32ea
	ld hl, $de86
	ld a, [bc]
	inc c
	ld [$ff8a], a
.asm_32f1
	ld a, [$ff8a]
	and a
	ret z
	dec a
	ld [$ff8a], a
	inc c
	inc c
	ld a, [bc]
	inc c
	ld e, a
	ld a, [bc]
	inc c
	ld d, a
	push bc
	ld a, [de]
	and $1f
	ld b, a
	ld a, [de]
	inc de
	and $e0
	ld [$ff8b], a
	ld a, [de]
	and $c0
	rlca
	rlca
	add $08
	ld c, a
	ld a, [de]
	and $3f
	add $40
	ld d, a
	ld a, [$ff8b]
	ld e, a
.asm_331c
	ld a, c
	ld [hli], a
	ld a, e
	ld [hli], a
	add $20
	ld e, a
	ld a, d
	ld [hli], a
	adc $00
	ld d, a
	ld a, l
	cp $b6
	jr nz, .asm_332f
	ld l, $86
.asm_332f
	dec b
	jr nz, .asm_331c
	pop bc
	jr .asm_32f1

Func_3335:
	ld hl, $dd80
	ld b, $21
	sub a
.asm_333b
	ld [hli], a
	dec b
	jr nz, .asm_333b
	ret

INCBIN "baserom.gbc", $3340, $392e - $3340

Func_392e:
	ld hl, $de86
	ld b, $30
	sub a
.asm_3934
	ld [hli], a
	dec b
	jr nz, .asm_3934
	ret

Func_3939:
	ld a, [hPaused]
	and a
	ret nz
	sub a
	ld [$ffe8], a
	ld hl, $ffdb
	ld a, [hCameraXOffset]
	add $a0
	ld [hli], a
	ld a, [hCameraXOffset + 1]
	adc $00
	ld [hli], a
	ld a, [hPlayerXPos]
	add $08
	ld [hli], a
	ld a, [hPlayerXPos + 1]
	adc $00
	ld [hli], a
	ld a, [$ffaf]
	ld b, $1e
	rra
	jr nc, .asm_3960
	srl b
.asm_3960
	ld a, [hPlayerYPos]
	sub b
	ld [hli], a
	ld a, [hPlayerYPos + 1]
	sbc 0
	ld [hli], a
	ld a, [hli]
	ld [MBC5RomBank], a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	inc hl
	ld a, [hCameraXOffset]
	ld c, a
	ld a, [hCameraXOffset + 1]
	ld b, a
.asm_3977
	ld a, [hld]
	inc a
	jr z, .asm_3992
	ld a, [hli]
	sub c
	ld e, a
	ld a, [hl]
	sbc b
	ld d, a
	jr nc, .asm_398b
	ld a, e
	add $c0
	ld a, d
	adc $02
	jr nc, .asm_3991
.asm_398b
	ld de, $fffa
	add hl, de
	jr .asm_3977
.asm_3991
	dec hl
.asm_3992
	ld de, $6
	add hl, de
	ld a, [hli]
	sub c
	ld e, a
	ld a, [hld]
	sbc b
	ld d, a
	jr nc, .asm_39a6
	ld a, e
	add $c0
	ld a, d
	adc $02
	jr nc, .asm_3992
.asm_39a6
	ld a, l
	ld [$ffe2], a
	ld a, h
	ld [$ffe3], a
	ld a, [hCameraYOffset]
	add $e0
	ld e, a
	ld a, [hCameraYOffset + 1]
	adc $ff
	ld d, a
	inc bc
	ld a, [$ffe1]
	ld [MBC5RomBank], a
.asm_39bc
	ld a, [hli]
	sub c
	ld a, [hli]
	sbc b
	ret nc
	ld a, [hli]
	sub c
	ld a, [hli]
	sbc b
	jr c, .asm_39e6
	push hl
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [hli]
	sub e
	ld a, [hld]
	sbc d
	jr nz, .asm_39e5
	ld a, [hld]
	sub e
	cp $c0
	jr nc, .asm_39e5
	push bc
	push de
	ld a, [hld]
	ld b, a
	ld a, [hli]
	ld c, a
	inc hl
	ld a, $01
	ld [MBC5RomBank], a
	push bc
	ret
.asm_39e5
	pop hl
.asm_39e6
	inc hl
	inc hl
	jr .asm_39bc

INCBIN "baserom.gbc", $39ea, $39f1 - $39ea

Func_39f1:
	ld a, $06
	ld [MBC5RomBank], a
	ld a, [hli]
	ld [$ffe1], a
	ld a, [hli]
	ld [$ffe2], a
	ld a, [hli]
	ld [$ffe3], a
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	ld a, [$ffe1]
	ld [MBC5RomBank], a
	ld hl, $d500
	ld de, $400
.asm_3a0f
	ld a, [bc]
	inc bc
	ld [hli], a
	dec de
	ld a, e
	or d
	jr nz, .asm_3a0f
	sub a
	ld [$ffe8], a
	ld hl, $ffdb
	ld a, [hCameraXOffset]
	add $a0
	ld [hli], a
	ld a, [hCameraXOffset + 1]
	adc $00
	ld [hli], a
	ld a, [hPlayerXPos]
	add $08
	ld [hli], a
	ld a, [hPlayerXPos + 1]
	adc $00
	ld [hli], a
	ld a, [hPlayerYPos]
	sub $1e
	ld [hli], a
	ld a, [hPlayerYPos + 1]
	sbc 0
	ld [hli], a
	sub a
	ld [$ffe9], a
	ld [$ffea], a
	pop hl
	ret

INCBIN "baserom.gbc", $3a42, $3a4d - $3a42

Func_3a4d:
	ld a, [hli]
	ld e, a
	ld a, [hli]
	ld d, a
.asm_3a51
	ld a, [hli]
	cp $ff
	ret z
	and a
	jr z, Func_3a4d
	push hl
	sub $30
	ld l, a
	ld h, $00
	add hl, hl
	add hl, hl
	add hl, hl
	add hl, hl
	ld bc, $c000
	add hl, bc
	ld b, h
	ld c, l
.asm_3a68
	ld a, [bc]
	inc c
	ld l, a
	ld a, [bc]
	inc c
	ld h, a
	cpl
	and l
	ld l, a
	ld a, [de]
	and h
	or l
	ld [de], a
	inc e
	ld a, [de]
	and h
	ld [de], a
	inc de
	ld a, c
	and $0f
	jr nz, .asm_3a68
	pop hl
	jr .asm_3a51

Func_3a82:
	ld a, $05
	ld [MBC5RomBank], a
	ld hl, $731c
	ld bc, $0
	call Func_3ca6
	ld hl, $deed
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	ld a, [hli]
	ld e, a
	ld a, [hli]
	ld d, a
	ld a, [hli]
	ld [$ff8a], a
	ld a, [hli]
	add a
	jr nc, .asm_3ae5
.asm_3aa2
	call WaitHBlankStart
	ld a, [bc]
	inc c
	ld [de], a
	inc e
	ld a, [bc]
	ld [de], a
	ld hl, $f
	add hl, bc
	ld b, h
	ld c, l
	ld hl, $f
	add hl, de
	ld d, h
	ld e, l
	ld a, [$ff8a]
	dec a
	ld [$ff8a], a
	jr nz, .asm_3aa2
	ld hl, $def3
	dec [hl]
	jp z, .asm_3b4c
	ld hl, $deed
	ld a, c
	and $0f
	cp $0e
	jr nz, .asm_3ade
	ld a, c
	sub $0e
	ld [hli], a
	ld a, b
	ld [hli], a
	ld a, [hl]
	add $12
	ld [hli], a
	ld a, [hl]
	adc $01
	ld [hl], a
	ret
.asm_3ade
	inc [hl]
	inc [hl]
	inc l
	inc l
	inc [hl]
	inc [hl]
	ret
.asm_3ae5
	add a
	jr nc, .asm_3b54
	ld a, [hl]
	and $07
	add $8e
	ld l, a
	ld a, $73
	adc $00
	ld h, a
	ld a, [hl]
	ld [$ff8b], a
.asm_3af6
	call WaitHBlankStart
	ld a, [$ff8b]
	ld l, a
	cpl
	ld h, a
	push hl
	ld a, [bc]
	inc c
	and l
	ld l, a
	ld a, [de]
	and h
	or l
	ld [de], a
	inc e
	pop hl
	ld a, [bc]
	inc bc
	and l
	ld l, a
	ld a, [de]
	and h
	or l
	ld [de], a
	inc de
	ld a, c
	and $0f
	jr nz, .asm_3b28
	ld hl, $def4
	ld a, [hli]
	add c
	ld c, a
	ld a, [hl]
	adc b
	ld b, a
	ld a, e
	add $10
	ld e, a
	ld a, d
	adc $01
	ld d, a
.asm_3b28
	ld a, [$ff8a]
	dec a
	ld [$ff8a], a
	jr nz, .asm_3af6
	ld hl, $def3
	dec [hl]
	jr z, .asm_3b4c
	ld a, [hl]
	and $07
	ret nz
	ld hl, $deed
	ld bc, $10
	ld a, [hl]
	add c
	ld [hli], a
	ld a, [hl]
	adc b
	ld [hli], a
	ld a, [hl]
	add c
	ld [hli], a
	ld a, [hl]
	adc b
	ld [hl], a
	ret
.asm_3b4c
	ld hl, $def2
	ld a, [hl]
	and $3f
	ld [hl], a
	ret
.asm_3b54
	add a
	ret nc
	ld hl, $def6
	dec [hl]
	ret nz
	inc l
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld bc, $deed
	ld a, [hli]
	ld [bc], a
	inc c
	ld a, [hli]
	ld [bc], a
	inc c
	ld a, [hli]
	ld [bc], a
	inc c
	ld a, [hli]
	ld [bc], a
	inc c
	ld a, [hli]
	ld e, a
	swap a
	and $f0
	ld [$ff8e], a
	ld a, e
	swap a
	and $0f
	ld [$ff8f], a
	ld a, [hli]
	ld d, a
	bit 7, [hl]
	jr z, .asm_3b8c
	sla d
	sla d
	sla d
	ld a, e
	jr .asm_3b97
.asm_3b8c
	sla e
	sla e
	sla e
	ld a, d
	ld d, e
	add a
	add a
	add a
.asm_3b97
	ld [bc], a
	inc c
	ld a, [hli]
	ld [bc], a
	inc c
	ld a, d
	ld [bc], a
	inc c
	ld a, [$ff8e]
	sub $10
	ld [bc], a
	inc c
	ld a, [$ff8f]
	sbc 0
	ld [bc], a
	inc c
	ld a, [hli]
	ld [bc], a
	inc c
	ld a, l
	ld [bc], a
	inc c
	ld a, h
	ld [bc], a
	ret

Func_3bb4:
	ld a, $06
	ld [MBC5RomBank], a
	ld a, [hli]
	ld [$def7], a
	ld a, [hli]
	ld [$def8], a
	push hl
	ld hl, vBGMap
	ld bc, $400
.asm_3bc8
	ld a, $7f
	ld [hli], a
	dec bc
	ld a, c
	or b
	jr nz, .asm_3bc8
	ld hl, $9841
	ld bc, $e
	ld a, $83
	ld d, $0e
.asm_3bda
	ld e, $12
.asm_3bdc
	ld [hli], a
	inc a
	dec e
	jr nz, .asm_3bdc
	add hl, bc
	dec d
	jr nz, .asm_3bda
	ld a, $05
	ld [MBC5RomBank], a
	ld hl, $def7
	ld a, [hli]
	ld h, [hl]
	ld l, a
.asm_3bf0
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	ld a, [hli]
	ld e, a
	ld a, [hli]
	ld d, a
	ld a, [hli]
	ld [$ff8a], a
	ld a, [hli]
	ld [$ff8b], a
	push hl
.asm_3bff
	ld a, [$ff8a]
	ld [$ff8c], a
.asm_3c03
	ld h, b
	ld l, c
.asm_3c05
	ld a, [hli]
	and a
	jr nz, .asm_3c19
	ld a, l
	and $0f
	jr nz, .asm_3c05
.asm_3c0e
	ld a, [de]
	inc de
	ld [bc], a
	inc bc
	ld a, c
	and $0f
	jr nz, .asm_3c0e
	jr .asm_3c25
.asm_3c19
	ld hl, $10
	add hl, bc
	ld b, h
	ld c, l
	ld hl, $10
	add hl, de
	ld d, h
	ld e, l
.asm_3c25
	ld a, [$ff8c]
	dec a
	ld [$ff8c], a
	jr nz, .asm_3c03
	ld a, [$ff8a]
	cpl
	inc a
	ld l, a
	ld h, $ff
	add hl, hl
	add hl, hl
	add hl, hl
	add hl, hl
	add hl, de
	ld de, $120
	add hl, de
	ld d, h
	ld e, l
	ld a, [$ff8b]
	dec a
	ld [$ff8b], a
	jr nz, .asm_3bff
	pop hl
	ld a, [hli]
	inc hl
	and $20
	jr nz, .asm_3bf0
	ld a, $20
	ld [$def2], a
	ld a, $3c
	ld [$def6], a
	pop hl
	ret

ReadJoyPad_Home:
	ld a, Bank(ReadJoyPad)
	ld [MBC5RomBank], a
	jp ReadJoyPad

TryTogglePause:
	ld a, [wNewKeys]
	bit PADB_START, a
	ret z
	ld a, [hPaused]
	cpl
	ld [hPaused], a
	and a
	jp z, ResumeMusicHome
	jp PauseMusicHome

Func_3c72:
	sub a
	ld hl, wNewKeys
	ld [hld], a
	cpl
	ld [hl], a
	ret

INCBIN "baserom.gbc", $3c7a, $3c98 - $3c7a

Func_3c98:
	ld a, [hCameraXOffset]
	ld e, a
	ld a, c
	sub e
	ld c, a
	ld a, [hCameraYOffset]
	ld e, a
	ld a, b
	sub e
	ld b, a
	jr Func_3ca6

Func_3ca6:
	ld a, [hli]
	ld e, a
	ld a, [hli]
	ld d, a
	push de
	ld a, [hActiveSprites]
	ld e, a
	ld d, $df
	ret

INCBIN "baserom.gbc", $3cb1, $3d96 - $3cb1

ClearOAMBufferHome:
	ld a, Bank(ClearOAMBuffer)
	ld [MBC5RomBank], a
	jp ClearOAMBuffer

WriteDMACodeToHRAM:
	ld hl, DMARoutine
	ld c, (hDMARoutine & $ff)
	ld b, 10
.loop
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .loop
	ld hl, wOAMBuffer
	ld b, wOAMBufferEnd - wOAMBuffer
	sub a
.clear
	ld [hli], a
	dec b
	jr nz, .clear
	call hDMARoutine
	sub a
	ld [hActiveSprites], a
	ret

DMARoutine:
	ld a, wOAMBuffer >> 8
	ld [rDMA], a
	ld a, $28
.waitLoop
	dec a
	jr nz, .waitLoop
	ret

TryInitNextScreenHome:
	ld a, Bank(TryInitNextScreen)
	ld [MBC5RomBank], a
	jp TryInitNextScreen

Func_3dce:
	call Func_3e3d
	ld a, Bank(Func_1759b)
	ld [MBC5RomBank], a
	ld bc, $1fd
	jp Func_1759b

Func_3ddc:
	ld a, [$defc]
	and a
	ret nz
	call Func_3e47
	ld a, Bank(Func_1759b)
	ld [MBC5RomBank], a
	ld bc, $ff0c
	jp Func_1759b

INCBIN "baserom.gbc", $3def, $3dfb - $3def

TickMusicEngineHome:
	ld a, Bank(TickMusicEngine)
	ld [MBC5RomBank], a
	jp TickMusicEngine

PauseMusicHome:
	ld a, Bank(PauseMusic)
	ld [MBC5RomBank], a
	jp PauseMusic

ResumeMusicHome:
	ld a, Bank(ResumeMusic)
	ld [MBC5RomBank], a
	jp ResumeMusic

Func_3e13:
	ld a, Bank(Func_8053)
	ld [MBC5RomBank], a
	jp Func_8053

Func_3e1b:
; play sound effect?
	push bc
	push de
	push hl
	ld b, a
	ld a, Bank(Func_8056)
	ld [MBC5RomBank], a
	ld a, b
	call Func_8056
	pop hl
	pop de
	pop bc
	ld a, $01
	ld [MBC5RomBank], a
	ret

Func_3e31:
	sub a
	ld [$defe], a
	ld a, Bank(Func_8059)
	ld [MBC5RomBank], a
	jp Func_8059

Func_3e3d:
	ld a, Bank(Func_805c)
	ld [MBC5RomBank], a
	ld a, $04
	jp Func_805c

Func_3e47:
	ld a, Bank(Func_805f)
	ld [MBC5RomBank], a
	ld a, $04
	jp Func_805f

Func_3e51:
	ld a, [$defe]
	and a
	jr z, .asm_3e5a
	inc hl
	inc hl
	ret
.asm_3e5a
	ld a, $06
	ld [MBC5RomBank], a
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push hl
	ld a, $02
	ld [MBC5RomBank], a
	ld de, $3e6f
	push de
	push bc
	ret

INCBIN "baserom.gbc", $3e6f, $3e71 - $3e6f

Func_3e71:
	ld a, [$defe]
	and a
	ret nz
	push bc
	push de
	ld a, $02
	ld [MBC5RomBank], a
	ld bc, $3e83
	push bc
	push hl
	ret

INCBIN "baserom.gbc", $3e83, $3e8b - $3e83

InitNextScreen:
	sub a
	ld [hPaused], a
	ld sp, wStack
	call Func_3e13
	call WriteDMACodeToHRAM
	call WaitUntilSafeToAccessVRAM
	ld hl, wCurScreen
	inc [hl]
	ld a, [hl]
	add a
	ld c, a
	ld b, $00
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ld hl, Data_1af94
	jr nz, .load
	ld hl, Data_1b030
.load
	add hl, bc
	ld a, Bank(Data_1af94)
	ld [MBC5RomBank], a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	or h
	jp z, Start_
	call LoadData
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	push bc
	ret

SetInitialScreen:
	sub a
	ld [wCurScreen], a
	ret

INCLUDE "home/load.asm"

INCBIN "baserom.gbc", $3ff1, $4000 - $3ff1

SECTION "ROM Bank $01", ROMX[$4000], BANK[$1]

INCBIN "baserom.gbc", $4000, $7dfc - $4000

ResetInitialData:
	call WaitUntilSafeToAccessVRAM
	sub a
	ld [rIF], a
	ld [$ffff], a
	ld [rSC], a
	ld [rTAC], a
	ld [rSTAT], a
	ld a, $30
	ld [rP1], a
	ld hl, vTilesOB
	ld bc, $2000
	call ClearData
	ld hl, wRAMStart
	ld bc, wStack - wRAMStart - 4
	call ClearData
	ld hl, _HRAM
	ld bc, $7e
	call ClearData
	sub a
	ld [wLanguageSetting], a
	ld [wDifficultySetting], a
	ld [$deb6], a
	ld [wEnableLevelSkip], a
	ld hl, wPasswordCharacters
	ld [hli], a
	ld [hli], a
	ld [hl], a
	ret

; Fills a data region with 0 values.
; Input: hl = destination
;        bc = number of bytes to clear
ClearData:
	sub a
	ld [hli], a
	dec bc
	ld a, c
	or b
	jr nz, ClearData
	ret

INCBIN "baserom.gbc", $7e45, $8000 - $7e45

SECTION "ROM Bank $02", ROMX[$4000], BANK[$2]

INCBIN "baserom.gbc", $8000, $804a - $8000

TickMusicEngine:
	jp TickMusicEngine_

PauseMusic:
	jp PauseMusic_

ResumeMusic:
	jp ResumeMusic_

Func_8053:
	jp Func_853d

Func_8056:
	jp Func_891a

Func_8059:
	jp Func_8522

Func_805c:
	jp Func_895d

Func_805f:
	jp Func_8957

INCBIN "baserom.gbc", $8062, $8098 - $8062

Func_8098:
	jp Func_891d

ResumeMusic_:
	xor a
	ld [$db42], a
	jp Func_876e

PauseMusic_:
	xor a
	ld [rNR12], a
	ld [rNR22], a
	ld [rNR42], a
	inc a
	ld [$db42], a
	ld a, [$de27]
	and a
	jr nz, .asm_80b6
	xor a
	ld [rNR32], a
.asm_80b6
	ld a, $80
	ld [rNR14], a
	ld [rNR24], a
	ld [rNR44], a
	ld a, [$de27]
	and a
	ret nz
	ld a, $80
	ld [rNR34], a
	ret

INCBIN "baserom.gbc", $80c8, $80e6 - $80c8

TickMusicEngine_:
	ld a, [$db42]
	and a
	jp nz, Func_81c1
	ld h, $db
	call Func_81de
	inc h
	call Func_81de
	inc h
	call Func_81de
	inc h
	call Func_81de
	call Func_8a7f
	ld hl, $db25
	ld l, $25
	ld e, [hl]
	inc l
	ld d, [hl]
	ld l, $05
	ld a, [hli]
	add e
	ld [$ff13], a
	ld a, [hli]
	adc d
	ld b, [hl]
	cp b
	jr z, Func_8122
	ld b, a
	ld [hl], a
	ld l, $33
	ld a, b
	ld c, [hl]
	inc c
	dec c
	jr z, Func_8131
	jp Func_8128
Func_8122:
	ld l, $33
	ld a, [hl]
	and a
	jr z, Func_8133
Func_8128:
	ld [hl], $00
	dec l
	ld a, [hl]
	ld [rNR12], a
	ld a, b
	or $80
Func_8131:
	ld [rNR14], a
Func_8133:
	inc h
	ld l, $25
	ld e, [hl]
	inc l
	ld d, [hl]
	ld l, $05
	ld a, [hli]
	add e
	ld [$ff18], a
	ld a, [hli]
	adc d
	ld b, [hl]
	cp b
	jr z, .asm_8152
	ld b, a
	ld [hl], a
	ld l, $33
	ld a, b
	ld c, [hl]
	inc c
	dec c
	jr z, Func_8161
	jp Func_8158
.asm_8152
	ld l, $33
	ld a, [hl]
	and a
	jr z, Func_asm_8163
Func_8158:
	ld [hl], $00
	dec l
	ld a, [hl]
	ld [rNR22], a
	ld a, b
	or $80
Func_8161
	ld [rNR24], a
Func_asm_8163
	ld hl, $de27
	ld a, [hl]
	and a
	jr nz, Func_816b
	dec h
Func_816b:
	ld l, $25
	ld e, [hl]
	inc l
	ld d, [hl]
	ld l, $05
	ld a, [hli]
	add e
	ld [$ff1d], a
	ld a, [hli]
	adc d
	cp [hl]
	jr z, .asm_817e
	ld [rNR34], a
	ld [hl], a
.asm_817e
	inc l
	ld a, [hl]
	add $ce
	ld l, a
	adc $41
	sub l
	ld h, a
	ld a, [$db44]
	cp [hl]
	jr z, Func_8193
	ld a, [hl]
	ld [$db44], a
	ld [rNR32], a
Func_8193:
	ld hl, $db38
	ld c, [hl]
	inc h
	ld a, [hl]
	rlc a
	or c
	ld c, a
	inc h
	ld a, [$de27]
	and a
	jr z, .asm_81a5
	inc h
.asm_81a5
	ld l, $38
	ld a, [hl]
	rlc a
	rlc a
	or c
	ld c, a
	ld a, [$db46]
	or c
	ld c, a
	ld a, [$db43]
	and a
	ld a, c
	jr nz, .asm_81bc
	ld a, $ff
.asm_81bc
	ld [$ff25], a
	jp Func_86ca

Func_81c1:
	call Func_86ca
	ld h, $de
	call Func_81de
	call Func_816b
	jr Func_8193

INCBIN "baserom.gbc", $81ce, $81de - $81ce

Func_81de:
	ld l, $27
	ld a, [hl]
	and a
	ret z
	ld l, $2f
	ld a, [hl]
	and a
	call nz, Func_866d
	ld l, $2c
	ld a, [hl]
	and a
	call nz, Func_863c
	ld l, $02
	ld e, [hl]
	inc l
	ld d, [hl]
	ld l, $0a
	dec [hl]
	call z, $427f
	ld l, $04
	bit 0, [hl]
	jr nz, .asm_8266
.asm_8202
	ld l, $0b
	ld a, [hli]
	add [hl]
	ld [hli], a
	add [hl]
	inc l
	add [hl]
	inc l
	add [hl]
	cp $50
	jr c, .asm_8211
	xor a
.asm_8211
	add a
	ld c, a
	ld b, $48
	ld l, $05
	ld a, [bc]
	inc c
	ld [hli], a
	ld a, [bc]
	ld [hl], a
	call $48a2
	call $4447
	ld l, $04
	bit 3, [hl]
	ret z
	ld l, $21
	ld a, [hl]
	and a
	jr z, .asm_822f
	dec [hl]
	ret
.asm_822f
	ld l, $04
	bit 4, [hl]
	jr z, .asm_824c
	ld l, $23
	dec [hl]
	jr nz, .asm_8242
	inc l
	ld a, [hld]
	ld [hl], a
	ld l, $04
	res 4, [hl]
	ret
.asm_8242
	ld l, $22
	ld a, [hl]
	ld l, $25
	add [hl]
	ld [hli], a
	ret nc
	inc [hl]
	ret
.asm_824c
	ld l, $23
	dec [hl]
	jr nz, .asm_8259
	inc l
	ld a, [hld]
	ld [hl], a
	ld l, $04
	set 4, [hl]
	ret
.asm_8259
	ld l, $22
	ld c, [hl]
	ld l, $25
	ld a, [hl]
	sub c
	ld [hli], a
	ret nc
	dec [hl]
	ret
.asm_8264
	ld [hl], $00
.asm_8266
	ld l, $1d
	ld a, [hli]
	ld b, [hl]
	inc l
	add [hl]
	ld c, a
	jr nc, .asm_8270
	inc b
.asm_8270
	ld a, [bc]
	cp $6a
	jr z, .asm_8264
	cp $ff
	jr z, .asm_8202
	inc [hl]
	ld l, $0e
	ld [hl], a
	jr .asm_8202

INCBIN "baserom.gbc", $827f, $8522 - $827f

Func_8522:
	ld a, $ff
	ld [rNR52], a
	ld a, $70
	ld [$db4b], a
	ld a, $c5
	ld [$db4a], a
	xor a
	ld [$db45], a
	ld [$db42], a
	ld [$db47], a
	ld [$db5d], a
Func_853d:
	ld a, $70
	ld [$db49], a
	ld a, $20
	ld [$db48], a
	xor a
	ld [rNR12], a
	ld [rNR22], a
	ld [rNR32], a
	ld [rNR42], a
	ld [rNR14], a
	ld [rNR24], a
	ld [rNR34], a
	ld [rNR44], a
	ld [$db65], a
	ld [$db52], a
	ld [$db5c], a
	ld a, $88
	ld [$db46], a
	ld a, $77
	ld [rNR50], a
	ld h, $db
	call .asm_857b
	inc h
	call .asm_857b
	inc h
	call .asm_857b
	inc h
	jr .asm_857b
	pop af
.asm_857b
	ld a, h
	cp $de
	jr z, .asm_85aa
	xor a
	ld l, $38
	ld [hl], $11
	dec l
	ld [hl], a
	ld l, $27
	ld [hl], a
	ld l, $08
	ld [hl], a
	ld l, $04
	ld [hl], a
	ld l, $2f
	ld [hl], a
	ld l, $2c
	ld [hl], a
	ld l, $37
	ld [hl], a
	ld l, $0f
	ld [hld], a
	ld [hld], a
	ld [hl], $f4
	dec l
	dec l
	ld [hld], a
	inc a
	ld [hl], a
	ld l, $33
	ld [hld], a
	dec a
	ld [hl], a
	ret
.asm_85aa
	xor a
	ld [$de27], a
	ld [$de08], a
	ld [$db5e], a
	ld [$db5f], a
	dec a
	ld [$db44], a
	jp Func_876e

INCBIN "baserom.gbc", $85be, $863c - $85be

Func_863c:
	ld l, $2d
	dec [hl]
	ret nz
	ld l, $2c
	ld a, [hli]
	ld [hli], a
	ld a, [hl]
	inc a
	ld [hl], a
	dec a
	jr z, .asm_8655
	dec a
	jr z, .asm_865a
	dec a
	jr z, .asm_8655
	dec a
	jr z, .asm_865f
	ld [hl], $01
.asm_8655
	ld l, $38
	ld [hl], $11
	ret
.asm_865a
	ld l, $38
	ld [hl], $01
	ret
.asm_865f
	ld l, $38
	ld [hl], $10
	ret

INCBIN "baserom.gbc", $8664, $866d - $8664

Func_866d:
	ld l, $30
	dec [hl]
	ret nz
	ld l, $2f
	ld a, [hli]
	ld [hli], a
	ld a, [hl]
	inc a
	ld [hl], a
	dec a
	jr z, .asm_8686
	dec a
	jr z, .asm_868a
	dec a
	jr z, .asm_868e
	dec a
	jr z, .asm_868a
	ld [hl], $01
.asm_8686
	ld l, $80
	jr .asm_8690
.asm_868a
	ld l, $c0
	jr .asm_8690
.asm_868e
	ld l, $00
.asm_8690
	ld a, h
	cp $db
	jr nz, .asm_8699
	ld a, l
	ld [rNR11], a
	ret
.asm_8699
	ld a, l
	ld [rNR21], a
	ret

Func_869d:
	ld [$db64], a
	ld a, l
	ld [$db60], a
	ld a, h
	ld [$db61], a
	jr .asm_86b9
	ld a, [de]
	ld [$db64], a
	inc de
	ld a, [de]
	ld [$db60], a
	inc de
	ld a, [de]
	ld [$db61], a
	inc de
.asm_86b9
	xor a
	ld [$db62], a
	ld [$db63], a
	inc a
	ld [$db65], a
	ret

Func_86c5:
	xor a
	ld [$db65], a
	ret

Func_86ca:
	ld a, [$db65]
	and a
	jr nz, .asm_86d9
	ld a, [rNR50]
	and a
	ret z
	ld a, $77
	ld [rNR50], a
	ret
.asm_86d9
	ld a, [$db63]
	and a
	jr z, .asm_86e4
	dec a
	ld [$db63], a
	ret
.asm_86e4
	ld hl, $db60
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [$db62]
	add l
	ld l, a
	adc h
	sub l
	ld h, a
	ld a, [hl]
	cp $6a
	jr z, .asm_870b
	cp $ff
	jr z, Func_86c5
	ld [rNR50], a
	ld a, [$db62]
	inc a
	ld [$db62], a
	ld a, [$db64]
	ld [$db63], a
	ret
.asm_870b
	xor a
	ld [$db62], a
	jr .asm_86e4

INCBIN "baserom.gbc", $8711, $876e - $8711

Func_876e:
	xor a
	ld [rNR30], a
	ld c, (_AUD3WAVERAM & $ff)
	ld hl, $db4c
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	ld a, [hl]
	ld [$ff00+c], a
	ld a, [$db42]
	and a
	ret nz
	ld a, $80
	ld [$dd07], a
	ld [rNR30], a
	ld [rNR34], a
	ret

INCBIN "baserom.gbc", $87b7, $891a - $87b7

Func_891a:
	jp Func_8098

Func_891d:
	ld [$de27], a
	ld c, a
	ld a, $11
	ld [$de38], a
	xor a
	ld [$de04], a
	ld [$de0b], a
	ld [$de2f], a
	ld [$de2c], a
	ld [$de0e], a
	inc a
	ld [$de0a], a
	ld a, $f4
	ld [$de0d], a
	ld a, c
	ld de, $de02
	add a
	add $a4
	ld l, a
	adc $71
	sub l
	ld h, a
	ld a, [hli]
	ld [de], a
	inc de
	ld a, l
	ld l, e
	ld e, a
	ld a, h
	ld h, d
	ld d, a
	ld a, [de]
	ld [hl], a
	ret

Func_8957:
	ld hl, $77ee
	jp Func_869d

Func_895d:
	ld hl, $77f7
	jp Func_869d

INCBIN "baserom.gbc", $8963, $8a7f - $8963

Func_8a7f:
	ld a, [$db47]
	and a
	jr z, .asm_8a89
	dec a
	ld [$db47], a
.asm_8a89
	ld hl, $db54
	dec [hl]
	call z, $4994
	ld a, [$db5c]
	and a
	ret z
	ld a, [$db5e]
	and a
	jr z, .asm_8aa0
	dec a
	ld [$db5e], a
	ret
.asm_8aa0
	ld a, [$db5f]
	ld [$db5e], a
	ld a, [$db57]
	ld h, a
	ld a, [$db58]
	ld l, a
	ld a, [$db5b]
	ld e, a
	inc a
	ld [$db5b], a
	ld d, $00
	add hl, de
	ld a, [hl]
	cp $ff
	jr z, .asm_8b1b
	ld [$ff22], a
	ld a, [$db59]
	and a
	jr z, .asm_8aea
	ld h, a
	ld a, [$db5a]
	ld l, a
	add hl, de
	ld c, $00
	ld a, [$db47]
	and a
	jr nz, .asm_8ad8
	ld a, [$db5d]
	ld c, a
.asm_8ad8
	ld a, [hl]
	cp $ff
	jr z, .asm_8aea
	swap c
	sub c
	jr nc, .asm_8ae4
	and $0f
.asm_8ae4
	ld [rNR42], a
	ld a, $80
	ld [rNR44], a
.asm_8aea
	ld a, [$db47]
	and a
	ret nz
	ld a, [$db4e]
	and a
	ret z
	ld b, a
	ld a, [$db5b]
	dec a
	jr nz, .asm_8b01
	ld a, $88
	ld [$db46], a
	ret
.asm_8b01
	sub b
	jr nz, .asm_8b0a
	ld a, $08
	ld [$db46], a
	ret
.asm_8b0a
	sub b
	jr nz, .asm_8b13
	ld a, $80
	ld [$db46], a
	ret
.asm_8b13
	sub b
	ret nz
	ld a, $88
	ld [$db46], a
	ret
.asm_8b1b
	xor a
	ld [$db5b], a
	ld [$db5c], a
	ret

INCBIN "baserom.gbc", $8b23, $C000 - $8b23

SECTION "ROM Bank $03", ROMX[$4000], BANK[$3]

WarnerBrosCopyrightLogoTiles:
	INCBIN "gfx/warner_bros_copyright/logo.interleave.2bpp.lz"
WarnerBrosCopyrightTrademarkTiles:
	INCBIN "gfx/warner_bros_copyright/trademark.2bpp.lz"
WarnerBrosCopyrightLolaBunnyTiles:
	INCBIN "gfx/warner_bros_copyright/lola_bunny.2bpp.lz"

LanguageSelectFontTiles:
	INCBIN "gfx/language_select/font.2bpp.lz"

INCBIN "baserom.gbc", $c944, $ccff - $c944

FarmSceneTiles:
	INCBIN "gfx/titlescreen/background.2bpp.lz"

INCBIN "baserom.gbc", $d674, $da76 - $d674

InfogramesCopyrightTiles:
	INCBIN "gfx/infogrames_copyright/background.2bpp.lz"

StudioCameraArrowTiles:
	INCBIN "gfx/studio/camera_arrow.interleave.2bpp.lz"

INCBIN "baserom.gbc", $dde7, $f545 - $dde7

WarnerBrosCopyrightAmpersandTiles:
	INCBIN "gfx/warner_bros_copyright/ampersand.2bpp"

INCBIN "baserom.gbc", $f585, $f610 - $f585

Func_f610:
	ld hl, $dde5
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [hl]
	cp $ff
	jp z, InitNextScreen
	ld a, [hActiveSprites]
	ld e, a
	ld d, $df
.asm_f621
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
.asm_f625
	ld a, b
	ld [de], a
	inc e
	ld a, c
	ld [de], a
	inc e
	add $08
	ld c, a
	ld a, [hli]
	sub $40
	add a
	add $34
	ld [de], a
	inc e
	sub a
	ld [de], a
	inc e
	ld a, [hl]
	and a
	jr nz, .asm_f640
	inc hl
	jr .asm_f621
.asm_f640
	cp $01
	jr nz, .asm_f625
	ld a, e
	ld [hActiveSprites], a
	ld a, [hFrameCounter]
	cp $ff
	ret nz
	inc hl
	ld a, l
	ld [$dde5], a
	ld a, h
	ld [$dde6], a
	ret

INCBIN "baserom.gbc", $f656, $10000 - $f656

SECTION "ROM Bank $04", ROMX[$4000], BANK[$4]

INCBIN "baserom.gbc", $10000, $105d6 - $10000

StudioCeilingFloorTiles:
	INCBIN "gfx/studio/ceiling_floor.2bpp.lz"
StudioCeilingFloorTilemap:
	INCBIN "gfx/studio/ceiling_floor.tilemap.lz"
StudioTiles:
	INCBIN "gfx/studio/tiles.2bpp.lz"
StudioMetatiles:
	INCBIN "gfx/studio/metatiles.bin.lz"
StudioMap:
	INCBIN "data/levels/studio.vdmap.lz"

INCBIN "baserom.gbc", $11387, $14000 - $11387

SECTION "ROM Bank $05", ROMX[$4000], BANK[$5]

INCBIN "baserom.gbc", $14000, $16e8c - $14000

INCLUDE "data/passwords.asm"

INCBIN "baserom.gbc", $16eab, $17568 - $16eab

TryInitNextScreen:
	ld a, [hPaused]
	and a
	ret nz
TryInitNextScreen_:
	ld hl, $defb
	dec [hl]
	ret nz
	ld a, $08
	ld [hli], a
	ld a, [hli]
	add a
	ld a, [hl]
	jr c, .asm_17586
	ret z
	add a, $03
	cp $0c
	jr nz, .asm_17589
	dec l
	sub a
	ld [hl], a
	ret
.asm_17586
	sub $03
	jp c, InitNextScreen
.asm_17589
	ld [hl], a
	ld hl, $3def
	ld c, a
	ld b, $00
	add hl, bc
	ld a, [hli]
	ld [rBGP], a
	ld a, [hli]
	ld [rOBP0], a
	ld a, [hl]
	ld [rOBP1], a
	ret

Func_1759b:
	ld hl, $defb
	ld a, $01
	ld [hli], a
	ld a, b
	ld [hli], a
	ld [hl], c
	jr TryInitNextScreen_

ClearOAMBuffer:
	ld a, [hPaused]
	and a
	ret nz
	call hDMARoutine
	ld a, [hActiveSprites]
	cp 161
	jr c, .ok
	ld a, 160
.ok
	srl a
	srl a
	ld b, a
	add a
	add b
	sub $79
	cpl
	ld hl, .asm_175c8
	ld c, a
	ld b, $00
	add hl, bc
	sub a
	jp hl
.asm_175c8
	ld [wOAMBuffer + $9c], a
	ld [wOAMBuffer + $98], a
	ld [wOAMBuffer + $94], a
	ld [wOAMBuffer + $90], a
	ld [wOAMBuffer + $8c], a
	ld [wOAMBuffer + $88], a
	ld [wOAMBuffer + $84], a
	ld [wOAMBuffer + $80], a
	ld [wOAMBuffer + $7c], a
	ld [wOAMBuffer + $78], a
	ld [wOAMBuffer + $74], a
	ld [wOAMBuffer + $70], a
	ld [wOAMBuffer + $6c], a
	ld [wOAMBuffer + $68], a
	ld [wOAMBuffer + $64], a
	ld [wOAMBuffer + $60], a
	ld [wOAMBuffer + $5c], a
	ld [wOAMBuffer + $58], a
	ld [wOAMBuffer + $54], a
	ld [wOAMBuffer + $50], a
	ld [wOAMBuffer + $4c], a
	ld [wOAMBuffer + $48], a
	ld [wOAMBuffer + $44], a
	ld [wOAMBuffer + $40], a
	ld [wOAMBuffer + $3c], a
	ld [wOAMBuffer + $38], a
	ld [wOAMBuffer + $34], a
	ld [wOAMBuffer + $30], a
	ld [wOAMBuffer + $2c], a
	ld [wOAMBuffer + $28], a
	ld [wOAMBuffer + $24], a
	ld [wOAMBuffer + $20], a
	ld [wOAMBuffer + $1c], a
	ld [wOAMBuffer + $18], a
	ld [wOAMBuffer + $14], a
	ld [wOAMBuffer + $10], a
	ld [wOAMBuffer + $c], a
	ld [wOAMBuffer + $8], a
	ld [wOAMBuffer + $4], a
	ld [wOAMBuffer], a
	ld [hActiveSprites], a
	ret

Func_17643:
	ld a, [hPaused]
	and a
	ret nz
	ld a, [$ffa4]
	add a
	jr c, .asm_17699
	jp z, Func_176e9
	ld bc, $b0
	ld de, hScore
	call Func_17791
.asm_17658
	ld hl, $ff98
	ld a, [hli]
	cp c
	ld a, [hli]
	jr nz, .asm_17663
	cp b
	jr z, .asm_17694
.asm_17663
	inc bc
	push bc
	push de
	ld a, [hl]
	add $10
	cp $b0
	jr nz, .asm_1766e
	sub a
.asm_1766e
	ld [hli], a
	add e
	ld e, a
	ld a, d
	adc $00
	ld d, a
	ld a, c
	and $0f
	jr nz, .asm_17682
	ld a, [hl]
	sub $10
	jr nc, .asm_17681
	ld a, $c0
.asm_17681
	ld [hl], a
.asm_17682
	call PrepareDrawMetatile
	call DrawMetatile_HBlank
	call DrawMetatileGBCAttributes_HBlank
	pop de
	pop bc
	ld a, [$ffa4]
	dec a
	ld [$ffa4], a
	jr nz, .asm_17658
.asm_17694
	ld hl, $ff50
	jr .asm_176e2
.asm_17699
	ld bc, hScore
	ld d, b
	ld e, c
	call Func_17791
.asm_176a1
	ld hl, $ff96
	ld a, [hli]
	cp c
	ld a, [hli]
	jr nz, .asm_176ac
	cp b
	jr z, .asm_176df
.asm_176ac
	push de
	inc l
	inc l
	ld a, [hl]
	sub $10
	jr nc, .asm_176b6
	ld a, $a0
.asm_176b6
	ld [hli], a
	add e
	ld e, a
	ld a, d
	adc $00
	ld d, a
	ld a, c
	and $0f
	jr nz, .asm_176cb
	ld a, [hl]
	add $10
	cp $d0
	jr nz, .asm_176ca
	sub a
.asm_176ca
	ld [hl], a
.asm_176cb
	dec bc
	push bc
	call PrepareDrawMetatile
	call DrawMetatile_HBlank
	call DrawMetatileGBCAttributes_HBlank
	pop bc
	pop de
	ld a, [$ffa4]
	inc a
	ld [$ffa4], a
	jr nz, .asm_176a1
.asm_176df
	ld hl, $10
.asm_176e2
	add hl, bc
	ld a, l
	ld [hCameraXOffset], a
	ld a, h
	ld [hCameraXOffset + 1], a
Func_176e9:
	ld a, [$ffa5]
	add a
	jr c, .asm_1773a
	jp z, Func_1778b
	ld bc, hScore
	ld de, $90
	call Func_17791
.asm_176fa
	ld hl, $ff9d
	ld a, [hld]
	cp d
	ld a, [hld]
	jr nz, .asm_17705
	cp e
	jr z, .asm_17735
.asm_17705
	inc de
	push bc
	push de
	ld a, [hl]
	sub $10
	jr nc, .asm_1770f
	ld a, $c0
.asm_1770f
	ld [hld], a
	add c
	ld c, a
	ld a, b
	adc $00
	ld b, a
	ld a, e
	and $0f
	jr nz, .asm_17723
	ld a, [hl]
	sub $10
	jr nc, .asm_17722
	ld a, $a0
.asm_17722
	ld [hl], a
.asm_17723
	call PrepareDrawMetatile
	call DrawMetatile_HBlank
	call DrawMetatileGBCAttributes_HBlank
	pop de
	pop bc
	ld a, [$ffa5]
	dec a
	ld [$ffa5], a
	jr nz, .asm_176fa
.asm_17735
	ld hl, $ff70
	jr .asm_17784
.asm_1773a
	ld bc, hScore
	ld d, b
	ld e, c
	call Func_17791
.asm_17742
	ld hl, $ff9f
	ld a, [hld]
	cp d
	ld a, [hld]
	jr nz, .asm_1774d
	cp e
	jr z, .asm_17781
.asm_1774d
	push bc
	dec l
	dec l
	ld a, [hl]
	add $10
	cp $d0
	jr nz, .asm_17758
	sub a
.asm_17758
	ld [hld], a
	add c
	ld c, a
	ld a, b
	adc $00
	ld b, a
	ld a, e
	and $0f
	jr nz, .asm_1776d
	ld a, [hl]
	add $10
	cp $b0
	jr nz, .asm_1776c
	sub a
.asm_1776c
	ld [hl], a
.asm_1776d
	dec de
	push de
	call PrepareDrawMetatile
	call DrawMetatile_HBlank
	call DrawMetatileGBCAttributes_HBlank
	pop de
	pop bc
	ld a, [$ffa5]
	inc a
	ld [$ffa5], a
	jr nz, .asm_17742
.asm_17781
	ld hl, $10
.asm_17784
	add hl, de
	ld a, l
	ld [hCameraYOffset], a
	ld a, h
	ld [hCameraYOffset + 1], a
Func_1778b:
	sub a
	ld [$ffa4], a
	ld [$ffa5], a
	ret

Func_17791:
	ld hl, hCameraXOffset
	ld a, [hli]
	add c
	ld c, a
	ld a, [hli]
	adc b
	ld b, a
	ld a, [hli]
	add e
	ld e, a
	ld a, [hl]
	adc d
	ld d, a
	ret

INCBIN "baserom.gbc", $177a1, $17929 - $177a1

Func_17929:
	ld a, [hPaused]
	and a
	ret nz
	ld hl, hPlayerXPos
	ld c, $cd
	ld b, $04
.asm_17934
	ld a, [hli]
	ld [$ff00+c], a
	inc c
	dec b
	jr nz, .asm_17934
	ld hl, $ffc4
	ld b, $18
	ld c, $02
	ld d, $28
	ld e, $03
	ld a, [$ffb0]
	cp $03
	jr nz, .asm_17957
	ld b, $14
	ld c, $00
	ld a, [hFrameCounter]
	and $07
	jr nz, .asm_17957
	ld c, $01
.asm_17957
	ld a, [$ffb0]
	cp $2a
	jr nz, .asm_1795f
	ld d, $10
.asm_1795f
	ld a, [$ffb0]
	cp $27
	jr nz, .asm_1796b
	ld b, $20
	ld c, $00
	ld e, $00
.asm_1796b
	ld a, [$ffb0]
	cp $24
	jr nz, .asm_1797c
	ld b, $10
	ld c, $00
	ld a, [hFrameCounter]
	rra
	jr c, .asm_1797c
	ld c, $01
.asm_1797c
	ld a, [$ffb0]
	cp $21
	jr nz, .asm_17984
	ld e, $00
.asm_17984
	ld a, [$ffb0]
	cp $1e
	jr nz, .asm_1798e
	ld b, $28
	ld c, $01
.asm_1798e
	ld a, [$ffb0]
	cp $1b
	jr nz, .asm_179a2
	ld b, $08
	ld c, $00
	ld e, $00
	ld a, [hFrameCounter]
	and $07
	jr nz, .asm_179a2
	ld c, $01
.asm_179a2
	ld a, [$ffb0]
	cp $18
	jr nz, .asm_179aa
	ld e, $00
.asm_179aa
	ld a, [$ffb0]
	cp $15
	jr nz, .asm_179bb
	ld b, $10
	ld c, $00
	ld a, [hFrameCounter]
	rra
	jr c, .asm_179bb
	ld c, $01
.asm_179bb
	ld a, [$ffb0]
	cp $12
	jr nz, .asm_179c3
	ld e, $00
.asm_179c3
	ld a, [$ffb0]
	cp $0c
	jr nz, .asm_179d7
	ld b, $10
	ld c, $00
	ld e, $00
	ld a, [hFrameCounter]
	and $03
	jr nz, .asm_179d7
	ld c, $01
.asm_179d7
	ld a, [$ffb0]
	cp $09
	jr nz, .asm_179df
	ld e, $00
.asm_179df
	ld a, [$ffb0]
	cp $06
	jr nz, .asm_179f0
	ld b, $20
	ld c, $00
	ld a, [hFrameCounter]
	rra
	jr c, .asm_179f0
	ld c, $01
.asm_179f0
	ld a, [$ffb5]
	and a
	jr z, .asm_179f7
	ld e, $00
.asm_179f7
	ld a, [$ffd1]
	sub $68
	ld a, [$ffd2]
	sbc 0
	jr c, .asm_17a06
	add a
	jr c, .asm_17a06
	ld d, $38
.asm_17a06
	ld a, [$ffb6]
	and a
	jr z, .asm_17a17
	ld b, $38
	ld c, $00
	ld a, [hFrameCounter]
	and $03
	jr nz, .asm_17a17
	ld c, $01
.asm_17a17
	ld a, [$ffaf]
	add a
	jr nc, .asm_17a31
	ld a, [$ffd6]
	sub $87
	ld a, [$ffd7]
	sbc $77
	jr c, .asm_17a31
	ld d, $08
	sub a
	ld [$ffd1], a
	ld [$ffd2], a
	ld b, $04
	ld c, $01
.asm_17a31
	ld a, [$ffb3]
	cp $1c
	jr c, .asm_17a3b
	ld b, $04
	ld c, $01
.asm_17a3b
	ld a, [hli]
	and a
	jr z, .asm_17a42
	add [hl]
	jr .asm_17a50
.asm_17a42
	ld a, [hl]
	bit 7, a
	jr nz, .asm_17a4c
	sub c
	jr nc, .asm_17a50
	jr .asm_17a4f
.asm_17a4c
	add c
	jr nc, .asm_17a50
.asm_17a4f
	sub a
.asm_17a50
	ld c, a
	add a
	ld a, b
	jr c, .asm_17a5a
	cp c
	jr nc, .asm_17a5f
	jr .asm_17a60
.asm_17a5a
	cpl
	inc a
	cp c
	jr nc, .asm_17a60
.asm_17a5f
	ld a, c
.asm_17a60
	ld c, l
	ld [hli], a
	ld a, [$ffc3]
	and a
	jr z, .asm_17a73
	dec a
	ld [$ffc3], a
	sub a
	ld [$ffd1], a
	ld [$ffd2], a
	ld a, $d0
	jr .asm_17a7d
.asm_17a73
	ld a, [hl]
	add e
	bit 7, a
	jr nz, .asm_17a7d
	cp d
	jr c, .asm_17a7d
	ld a, d
.asm_17a7d
	ld [hli], a
	ld a, [$ffc2]
	add a
	jr z, .asm_17a96
	jr c, .asm_17a8b
	ld a, $18
	ld b, $ff
	jr .asm_17a8f
.asm_17a8b
	ld a, $e8
	ld b, $01
.asm_17a8f
	ld [$ffc5], a
	ld a, [$ffc2]
	add b
	ld [$ffc2], a
.asm_17a96
	ld a, [hli]
	call Func_17aba
	ld a, b
	ld [$ffc7], a
	inc c
	ld a, [$ffcc]
	call Func_17aba
	ld [hl], b
	ld hl, $ffcf
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	ld a, [hPlayerYPos]
	sub c
	ld c, a
	ld a, [hPlayerYPos + 1]
	sbc b
	ld b, a
	ld a, [hl]
	add c
	ld [hli], a
	ld a, [hl]
	adc b
	ld [hl], a
	ret

Func_17aba:
	ld b, a
	ld d, $00
	db $f2
	add a
	jr nc, .asm_17ac3
	ld d, $ff
.asm_17ac3
	ld e, d
	add a
	rl e
	add a
	rl e
	add a
	rl e
	add b
	ld b, a
	ld a, [hl]
	adc e
	ld [hli], a
	ld a, [hl]
	adc d
	ld [hli], a
	ret

INCBIN "baserom.gbc", $17ad6, $17af0 - $17ad6

ReadJoyPad:
	ld a, [wEnableLevelSkip]
	and a
	jr z, .readJoyPad
	ld a, [wNewKeys]
	bit PADB_SELECT, a
	jr z, .readJoyPad
	ld a, [hPaused]
	and a
	jr z, .readJoyPad
	ld hl, $3e8b
	push hl
	jp ResumeMusicHome
.readJoyPad
	sub a
	ld c, a
	ld a, $20
	ld [$ff00+c], a
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld b, a
	ld a, $10
	ld [$ff00+c], a
	ld a, b
	and $0f
	swap a
	ld b, a
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	ld a, [$ff00+c]
	and $0f
	or b
	cpl
	ld b, a
	ld a, $30
	ld [$ff00+c], a
	ld a, [wHeldKeys]
	xor b
	and b
	ld [wNewKeys], a
	ld a, b
	ld [wHeldKeys], a
	ret

INCBIN "baserom.gbc", $17b39, $17dd6 - $17b39

SECTION "ROM Bank $06", ROMX[$4000], BANK[$6]

INCBIN "baserom.gbc", $18000, $1a5a3 - $18000

WarnerBrosCopyrightInteractiveEntertainmentTiles:
	INCBIN "gfx/warner_bros_copyright/interactive_entertainment.2bpp"

StudioCreditsTextTiles:
	INCBIN "gfx/studio/credits_text.interleave.2bpp.lz"

INCBIN "baserom.gbc", $1a84e, $1a89f - $1a84e

; Loads common sprite palettes and the specified BG and
; sprite palettes. Also clears the BG map attributes.
; Input: hl = pointer to palette data structure
LoadCGBPalettes:
	ld a, [hGameBoyColorDetection]
	cp GBC_MODE
	ret nz
	ld a, (1 << 7) | $28
	ld [rOCPS], a
	ld de, CommonSpritePalettes
	ld b, 3 ; number of palettes
.commonSpritePaletteLoop
	ld c, 6 ; number of color bytes
	sub a
	ld [rOCPD], a ; First two bytes are the transparent color in the sprite palette.
	ld [rOCPD], a
.commonSpriteColorLoop
	ld a, [de]
	inc de
	ld [rOCPD], a
	dec c
	jr nz, .commonSpriteColorLoop
	dec b
	jr nz, .commonSpritePaletteLoop
	ld a, $80
	ld [rBCPS], a
	ld a, [hli]
	ld b, a ; number of palettes
.backgroundPaletteLoop
	ld a, b
	and a
	jr z, .loadSpritePalettes
	dec b
	ld c, 8
.backgroundColorLoop
	ld a, [hli]
	ld [rBCPD], a
	dec c
	jr nz, .backgroundColorLoop
	jr .backgroundPaletteLoop
.loadSpritePalettes
	ld a, $80
	ld [rOCPS], a
	ld a, [hli]
	ld b, a
.spritePaletteLoop
	ld a, b
	and a
	jr z, .clearBank1BGMap
	dec b
	ld c, 6 ; number of color bytes
	sub a
	ld [rOCPD], a ; First two bytes are the transparent color in the sprite palette.
	ld [rOCPD], a
.spriteColorLoop
	ld a, [hli]
	ld [rOCPD], a
	dec c
	jr nz, .spriteColorLoop
	jr .spritePaletteLoop
.clearBank1BGMap
	ld a, 1
	ld [rVBK], a
	ld hl, vBGMap
	ld bc, $800
.clearLoop
	sub a
	ld [hli], a
	dec bc
	ld a, c
	or b
	jr nz, .clearLoop
	sub a
	ld [rVBK], a
	ret

Func_1a902:
	ld h, b
	ld l, c
	ld a, $80
	ld [rBCPS], a
	ld a, [hli]
	ld b, a
.paletteLoop
	ld a, b
	and a
	jr z, .done
	dec b
	ld c, 8
.colorLoop
	ld a, [hli]
	ld [rBCPD], a
	dec c
	jr nz, .colorLoop
	jr .paletteLoop
.done
	call ReadAndLoadCGBpalettes
	pop hl
	ret

ReadAndLoadCGBpalettes:
	ld a, [hli]
	ld h, [hl]
	ld l, a
	jp LoadCGBPalettesHome

INCBIN "baserom.gbc", $1a924, $1a93a - $1a924

InfogramesCopyrightScreenGBCPalettes:
	db 8 ; num background palettes
	; BG Palette 0
	RGB(0, 0, 0)
	RGB(10, 10, 10)
	RGB(21, 21, 21)
	RGB(31, 31, 31)

	; BG Palette 1
	RGB(0, 31, 0)
	RGB(0, 31, 0)
	RGB(0, 31, 0)
	RGB(0, 31, 0)

	; BG Palette 2
	RGB(0, 31, 0)
	RGB(0, 31, 0)
	RGB(0, 31, 0)
	RGB(0, 31, 0)

	; BG Palette 3
	RGB(31, 31, 31)
	RGB(28, 0, 0)
	RGB(31, 31, 0)
	RGB(21, 0, 22)

	; BG Palette 4
	RGB(0, 31, 0)
	RGB(0, 31, 0)
	RGB(0, 31, 0)
	RGB(0, 31, 0)

	; BG Palette 5
	RGB(0, 31, 0)
	RGB(31, 31, 31)
	RGB(16, 0, 16)
	RGB(0, 0, 0)

	; BG Palette 6
	RGB(31, 31, 31)
	RGB(0, 23, 0)
	RGB(0, 0, 23)
	RGB(0, 0, 0)

	; BG Palette 7
	RGB(31, 31, 31)
	RGB(0, 23, 0)
	RGB(31, 31, 0)
	RGB(0, 0, 23)

	db 0 ; num sprite palettes

WarnerBrosCopyrightScreenGBCPalettes:
	db 1 ; num background palettes
	; BG Palette 0
	RGB(31, 31, 31)
	RGB(31, 0, 0)
	RGB(15, 0, 0)
	RGB(7, 0, 0)

	db 2 ; num sprite palettes
	; OBJ Palette 0
	RGB(31, 0, 0)
	RGB(15, 0, 0)
	RGB(7, 0, 0)

	; OBJ Palette 1
	RGB(31, 31, 0)
	RGB(23, 8, 0)
	RGB(4, 4, 15)

INCBIN "baserom.gbc", $1a992, $1aa68 - $1a992

StudioScreenGBCPalettes:
	db 8 ; num background palettes
	db $F7, $6B, $CC, $36, $65, $19, $00, $00
	db $7F, $2B, $52, $0E, $E8, $00, $00, $00
	db $FF, $7F, $91, $4D, $88, $2C, $00, $00
	db $88, $7E, $3C, $2A, $90, $00, $00, $00
	db $FF, $7F, $AF, $7F, $88, $7E, $22, $66
	db $88, $7E, $EB, $0F, $EF, $08, $00, $00
	db $F7, $6B, $31, $46, $08, $21, $00, $00
	db $F7, $6B, $3C, $2A, $EF, $08, $00, $00

	db 5 ; num sprite palettes
	db $1E, $53, $38, $09, $00, $00
	db $BF, $02, $14, $01, $00, $00
	db $3C, $33, $6E, $01, $00, $00
	db $BD, $4B, $44, $02, $00, $00
	db $5D, $4A, $33, $01, $00, $00

INCBIN "baserom.gbc", $1aac8, $1af18 - $1aac8

; This only holds colors 1-3. The first transparent color is hardcoded
; in LoadCGBPalettes.
CommonSpritePalettes:
	; OBJ Palette 5
	RGB(31, 31, 31)
	RGB(14, 14, 14)
	RGB(0, 0, 0)

	; OBJ Palette 6
	RGB(31, 27, 0)
	RGB(19, 7, 0)
	RGB(0, 0, 0)

	; OBJ Palette 7
	RGB(31, 28, 20)
	RGB(31, 8, 0)
	RGB(0, 0, 0)

INCBIN "baserom.gbc", $1af2a, $1af94 - $1af2a

Data_1af94:
	dw $ffff
	dw Data_1b0cc ; SCREEN_COPYRIGHT_INFOGRAMES
	dw Data_1b0d9 ; SCREEN_COPYRIGHT_WARNER_BROS
	dw Data_1b129 ; SCREEN_LANGUAGE_SELECT
	dw $716f ; SCREEN_TITLESCREEN
	dw $7147 ; SCREEN_OPTIONS
	dw $7194 ; SCREEN_INTRO_SCENE
	dw Data_1b2ee ; SCREEN_STUDIO_ENTRANCE
	dw $71fc ; SCREEN_TREASURE_ISLAND_1_INTRO
	dw $73b6 ; SCREEN_TREASURE_ISLAND_1
	dw $7722 ; SCREEN_TREASURE_ISLAND_1_SUMMARY
	dw $7794 ; SCREEN_TREASURE_ISLAND_1_BONUS
	dw $720d ; SCREEN_TREASURE_ISLAND_2_INTRO
	dw $73ed ; SCREEN_TREASURE_ISLAND_2
	dw $7722 ; SCREEN_TREASURE_ISLAND_2_SUMMARY
	dw $779b ; SCREEN_TREASURE_ISLAND_2_BONUS
	dw $721e ; SCREEN_TREASURE_ISLAND_BOSS_INTRO
	dw $7472 ; SCREEN_TREASURE_ISLAND_BOSS
	dw $7722 ; SCREEN_TREASURE_ISLAND_BOSS_SUMMARY
	dw $77a2 ; SCREEN_TREASURE_ISLAND_BOSS_BONUS
	dw $7710 ; SCREEN_PASSWORD_1
	dw $7300 ; SCREEN_STUDIO_TREASURE_ISLAND
	dw $71c9 ; SCREEN_CRAZY_TOWN_1_INTRO
	dw $7348 ; SCREEN_CRAZY_TOWN_1
	dw $7722 ; SCREEN_CRAZY_TOWN_1_SUMMARY
	dw $77a9 ; SCREEN_CRAZY_TOWN_1_BONUS
	dw $71da ; SCREEN_CRAZY_TOWN_2_INTRO
	dw $737f ; SCREEN_CRAZY_TOWN_2
	dw $7722 ; SCREEN_CRAZY_TOWN_2_SUMMARY
	dw $77b0 ; SCREEN_CRAZY_TOWN_2_BONUS
	dw $71eb ; SCREEN_CRAZY_TOWN_BOSS_INTRO
	dw $7424 ; SCREEN_CRAZY_TOWN_BOSS
	dw $7722 ; SCREEN_CRAZY_TOWN_BOSS_SUMMARY
	dw $77b7 ; SCREEN_CRAZY_TOWN_BOSS_BONUS
	dw $7312 ; SCREEN_STUDIO_CRAZY_TOWN
	dw $722f ; SCREEN_TAZ_ZOO_1_INTRO
	dw $74c0 ; SCREEN_TAZ_ZOO_1
	dw $7722 ; SCREEN_TAZ_ZOO_1_SUMMARY
	dw $77be ; SCREEN_TAZ_ZOO_1_BONUS
	dw $7240 ; SCREEN_TAZ_ZOO_2_INTRO
	dw $74f7 ; SCREEN_TAZ_ZOO_2
	dw $7722 ; SCREEN_TAZ_ZOO_2_SUMMARY
	dw $77c5 ; SCREEN_TAZ_ZOO_2_BONUS
	dw $7251 ; SCREEN_TAZ_ZOO_BOSS_INTRO
	dw $752e ; SCREEN_TAZ_ZOO_BOSS
	dw $7722 ; SCREEN_TAZ_ZOO_BOSS_SUMMARY
	dw $77cc ; SCREEN_TAZ_ZOO_BOSS_BONUS
	dw $7719 ; SCREEN_PASSWORD_2
	dw $7324 ; SCREEN_STUDIO_TAZ_ZOO
	dw $7262 ; SCREEN_SPACE_STATION_1_INTRO
	dw $7588 ; SCREEN_SPACE_STATION_1
	dw $7722 ; SCREEN_SPACE_STATION_1_SUMMARY
	dw $77d3 ; SCREEN_SPACE_STATION_1_BONUS
	dw $7273 ; SCREEN_SPACE_STATION_2_INTRO
	dw $75bf ; SCREEN_SPACE_STATION_2
	dw $7722 ; SCREEN_SPACE_STATION_2_SUMMARY
	dw $77da ; SCREEN_SPACE_STATION_2_BONUS
	dw $7284 ; SCREEN_SPACE_STATION_BOSS_INTRO
	dw $75f6 ; SCREEN_SPACE_STATION_BOSS
	dw $7722 ; SCREEN_SPACE_STATION_BOSS_SUMMARY
	dw $77e1 ; SCREEN_SPACE_STATION_BOSS_BONUS
	dw $7336 ; SCREEN_STUDIO_SPACE_STATION
	dw $7295 ; SCREEN_FUDD_FOREST_1_INTRO
	dw $7638 ; SCREEN_FUDD_FOREST_1
	dw $7722 ; SCREEN_FUDD_FOREST_1_SUMMARY
	dw $77e8 ; SCREEN_FUDD_FOREST_1_BONUS
	dw $72a6 ; SCREEN_FUDD_FOREST_2_INTRO
	dw $766f ; SCREEN_FUDD_FOREST_2
	dw $7722 ; SCREEN_FUDD_FOREST_2_SUMMARY
	dw $77ef ; SCREEN_FUDD_FOREST_2_BONUS
	dw $72b7 ; SCREEN_FUDD_FOREST_BOSS_INTRO
	dw $76a6 ; SCREEN_FUDD_FOREST_BOSS
	dw $7722 ; SCREEN_FUDD_FOREST_BOSS_SUMMARY
	dw $7764 ; SCREEN_PROLOGUE_SCENE
	dw $777d ; SCREEN_CREDITS
	dw $0000
	dw $7113 ; SCREEN_GAME_OVER
	dw $0000

Data_1b030:
	dw $ffff
	dw Data_1bcb0 ; SCREEN_COPYRIGHT_INFOGRAMES
	dw Data_1b0d9 ; SCREEN_COPYRIGHT_WARNER_BROS
	dw Data_1b129 ; SCREEN_LANGUAGE_SELECT
	dw $7c63 ; SCREEN_TITLESCREEN
	dw $7147 ; SCREEN_OPTIONS
	dw $7c8d ; SCREEN_INTRO_SCENE
	dw Data_1b2ee ; SCREEN_STUDIO_ENTRANCE
	dw $71fc ; SCREEN_TREASURE_ISLAND_1_INTRO
	dw $7891 ; SCREEN_TREASURE_ISLAND_1
	dw $7722 ; SCREEN_TREASURE_ISLAND_1_SUMMARY
	dw $7794 ; SCREEN_TREASURE_ISLAND_1_BONUS
	dw $720d ; SCREEN_TREASURE_ISLAND_2_INTRO
	dw $78cd ; SCREEN_TREASURE_ISLAND_2
	dw $7722 ; SCREEN_TREASURE_ISLAND_2_SUMMARY
	dw $779b ; SCREEN_TREASURE_ISLAND_2_BONUS
	dw $721e ; SCREEN_TREASURE_ISLAND_BOSS_INTRO
	dw $79d9 ; SCREEN_TREASURE_ISLAND_BOSS
	dw $7722 ; SCREEN_TREASURE_ISLAND_BOSS_SUMMARY
	dw $77a2 ; SCREEN_TREASURE_ISLAND_BOSS_BONUS
	dw $7710 ; SCREEN_PASSWORD_1
	dw $7300 ; SCREEN_STUDIO_TREASURE_ISLAND
	dw $71c9 ; SCREEN_CRAZY_TOWN_1_INTRO
	dw $7819 ; SCREEN_CRAZY_TOWN_1
	dw $7722 ; SCREEN_CRAZY_TOWN_1_SUMMARY
	dw $77a9 ; SCREEN_CRAZY_TOWN_1_BONUS
	dw $71da ; SCREEN_CRAZY_TOWN_2_INTRO
	dw $7855 ; SCREEN_CRAZY_TOWN_2
	dw $7722 ; SCREEN_CRAZY_TOWN_2_SUMMARY
	dw $77b0 ; SCREEN_CRAZY_TOWN_2_BONUS
	dw $71eb ; SCREEN_CRAZY_TOWN_BOSS_INTRO
	dw $7909 ; SCREEN_CRAZY_TOWN_BOSS
	dw $7722 ; SCREEN_CRAZY_TOWN_BOSS_SUMMARY
	dw $77b7 ; SCREEN_CRAZY_TOWN_BOSS_BONUS
	dw $7312 ; SCREEN_STUDIO_CRAZY_TOWN
	dw $722f ; SCREEN_TAZ_ZOO_1_INTRO
	dw $7961 ; SCREEN_TAZ_ZOO_1
	dw $7722 ; SCREEN_TAZ_ZOO_1_SUMMARY
	dw $77be ; SCREEN_TAZ_ZOO_1_BONUS
	dw $7240 ; SCREEN_TAZ_ZOO_2_INTRO
	dw $799d ; SCREEN_TAZ_ZOO_2
	dw $7722 ; SCREEN_TAZ_ZOO_2_SUMMARY
	dw $77c5 ; SCREEN_TAZ_ZOO_2_BONUS
	dw $7251 ; SCREEN_TAZ_ZOO_BOSS_INTRO
	dw $7bcd ; SCREEN_TAZ_ZOO_BOSS
	dw $7722 ; SCREEN_TAZ_ZOO_BOSS_SUMMARY
	dw $77cc ; SCREEN_TAZ_ZOO_BOSS_BONUS
	dw $7719 ; SCREEN_PASSWORD_2
	dw $7324 ; SCREEN_STUDIO_TAZ_ZOO
	dw $7262 ; SCREEN_SPACE_STATION_1_INTRO
	dw $7a35 ; SCREEN_SPACE_STATION_1
	dw $7722 ; SCREEN_SPACE_STATION_1_SUMMARY
	dw $77d3 ; SCREEN_SPACE_STATION_1_BONUS
	dw $7273 ; SCREEN_SPACE_STATION_2_INTRO
	dw $7a71 ; SCREEN_SPACE_STATION_2
	dw $7722 ; SCREEN_SPACE_STATION_2_SUMMARY
	dw $77da ; SCREEN_SPACE_STATION_2_BONUS
	dw $7284 ; SCREEN_SPACE_STATION_BOSS_INTRO
	dw $7aad ; SCREEN_SPACE_STATION_BOSS
	dw $7722 ; SCREEN_SPACE_STATION_BOSS_SUMMARY
	dw $77e1 ; SCREEN_SPACE_STATION_BOSS_BONUS
	dw $7336 ; SCREEN_STUDIO_SPACE_STATION
	dw $7295 ; SCREEN_FUDD_FOREST_1_INTRO
	dw $7afb ; SCREEN_FUDD_FOREST_1
	dw $7722 ; SCREEN_FUDD_FOREST_1_SUMMARY
	dw $77e8 ; SCREEN_FUDD_FOREST_1_BONUS
	dw $72a6 ; SCREEN_FUDD_FOREST_2_INTRO
	dw $7b37 ; SCREEN_FUDD_FOREST_2
	dw $7722 ; SCREEN_FUDD_FOREST_2_SUMMARY
	dw $77ef ; SCREEN_FUDD_FOREST_2_BONUS
	dw $72b7 ; SCREEN_FUDD_FOREST_BOSS_INTRO
	dw $7b73 ; SCREEN_FUDD_FOREST_BOSS
	dw $7722 ; SCREEN_FUDD_FOREST_BOSS_SUMMARY
	dw $7cc2 ; SCREEN_PROLOGUE_SCENE
	dw $777d ; SCREEN_CREDITS
	dw $0000
	dw $7113 ; SCREEN_GAME_OVER
	dw $0000

Data_1b0cc:
	compressed_data InfogramesCopyrightTiles, $9550
	compressed_data InfogramesCopyrightTilemap, $9800
	db $ff
	dw InitInfogramesCopyrightScreen

Data_1b0d9:
	compressed_data WarnerBrosCopyrightTiles, $8830
	compressed_data WarnerBrosCopyrightEdgeTiles, $8000
	uncompressed_data WarnerBrosCopyrightUnderLicenseByTiles, $c000, $80
	uncompressed_data WarnerBrosCopyrightInteractiveEntertainmentTiles, $c080, $c0
	compressed_data WarnerBrosCopyrightTrademarkTiles, $c200
	compressed_data WarnerBrosCopyrightBugsBunnyTiles, $c560
	uncompressed_data WarnerBrosCopyrightAmpersandTiles, $c8e0, $40
	compressed_data WarnerBrosCopyrightLolaBunnyTiles, $c920
	compressed_data WarnerBrosCopyrightLogoTiles, $81c0
	db $ff
	dw InitWarnerBrosCopyrightScreen

INCBIN "baserom.gbc", $1b10f, $1b129 - $1b10f

Data_1b129:
	compressed_data WarnerBrosCopyrightTiles, $8830
	compressed_data WarnerBrosCopyrightEdgeTiles, $8000
	compressed_data LanguageSelectCarrotTiles, $81c0
	compressed_data LanguageSelectFontTiles, $c000
	compressed_data GameText, $c500
	db $ff
	dw Func_5ca

INCBIN "baserom.gbc", $1b145, $1b2c8 - $1b145

StudioScreenData:
	compressed_data StudioTiles, $8C80
	compressed_data StudioMetatiles, wMetatiles
	db $0F
	dw $7F8C, $C400
	compressed_data StudioMap, wLevelMap
	compressed_data StudioCeilingFloorTiles, $8840
	compressed_data StudioCeilingFloorTilemap, $9B00
	compressed_data StudioCameraArrowTiles, $8560
	db $ff
	dw $4065

Data_1b2ee:
	db $ff
	dw InitStudioScreen

INCBIN "baserom.gbc", $1b2f1, $1b77d - $1b2f1

Data_1b77d:
	compressed_data StudioCreditsTextTiles, $8340
	db $ff
	dw InitStudioCreditsScreen

INCBIN "baserom.gbc", $1b785, $1bc33 - $1b785

StudioScreenData_GBC:
	compressed_data StudioTilesGBC, $8C80
	compressed_data StudioMetatilesGBC, wMetatiles
	db $16
	dw $4701, $C400
	compressed_data StudioMapGBC, wLevelMap
	compressed_data StudioCeilingFloorTilesGBC, $8840
	compressed_data StudioCeilingFloorTilemapGBC, $9B00
	compressed_data StudioCameraArrowTiles, $8560
	compressed_data StudioTileAttributesGBC, $DA48
	compressed_data StudioCeilingFloorTileAttributesGBC, $D9BC
	db $ff
	dw $4065

INCBIN "baserom.gbc", $1bc63, $1bcb0 - $1bc63

Data_1bcb0:
	compressed_data InfogramesCopyrightGBCTiles, $9550
	compressed_data InfogramesCopyrightGBCTilemap, $9800
	compressed_data InfogramesCopyrightGBCAttributesTilemap, $d9d5
	db $ff
	dw InitInfogramesCopyrightScreen

INCBIN "baserom.gbc", $1bcc2, $1c000 - $1bcc2

SECTION "ROM Bank $07", ROMX[$4000], BANK[$7]

INCBIN "baserom.gbc", $1C000, $20000 - $1C000

SECTION "ROM Bank $08", ROMX[$4000], BANK[$8]

INCBIN "baserom.gbc", $20000, $24000 - $20000

SECTION "ROM Bank $09", ROMX[$4000], BANK[$9]

INCBIN "baserom.gbc", $24000, $27c51 - $24000

WarnerBrosCopyrightEdgeTiles:
	INCBIN "gfx/warner_bros_copyright/edge.2bpp.lz"

INCBIN "baserom.gbc", $27ced, $28000 - $27ced

SECTION "ROM Bank $0A", ROMX[$4000], BANK[$A]

INCBIN "baserom.gbc", $28000, $2bf2a - $28000

WarnerBrosCopyrightUnderLicenseByTiles:
	INCBIN "gfx/warner_bros_copyright/under_license_by.2bpp"

LanguageSelectCarrotTiles:
	INCBIN "gfx/language_select/carrot.interleave.2bpp.lz"

SECTION "ROM Bank $0B", ROMX[$4000], BANK[$B]

INCBIN "baserom.gbc", $2C000, $30000 - $2C000

SECTION "ROM Bank $0C", ROMX[$4000], BANK[$C]

INCBIN "baserom.gbc", $30000, $314b0 - $30000

GameText:
	INCBIN "data/game_text.bin.lz"

INCBIN "baserom.gbc", $31ae0, $34000 - $31ae0

SECTION "ROM Bank $0D", ROMX[$4000], BANK[$D]

INCBIN "baserom.gbc", $34000, $38000 - $34000

SECTION "ROM Bank $0E", ROMX[$4000], BANK[$E]

INCBIN "baserom.gbc", $38000, $3bd22 - $38000

WarnerBrosCopyrightBugsBunnyTiles:
	INCBIN "gfx/warner_bros_copyright/bugs_bunny.2bpp.lz"

InfogramesCopyrightTilemap:
	INCBIN "gfx/infogrames_copyright/background.tilemap.lz"

SECTION "ROM Bank $0F", ROMX[$4000], BANK[$F]

INCBIN "baserom.gbc", $3C000, $3fceb - $3C000

WarnerBrosCopyrightTiles:
	INCBIN "gfx/warner_bros_copyright/background.2bpp.lz"

INCBIN "baserom.gbc", $3ff8c, $40000 - $3ff8c

SECTION "ROM Bank $10", ROMX[$4000], BANK[$10]

INCBIN "baserom.gbc", $40000, $44000 - $40000

SECTION "ROM Bank $11", ROMX[$4000], BANK[$11]

INCBIN "baserom.gbc", $44000, $48000 - $44000

SECTION "ROM Bank $12", ROMX[$4000], BANK[$12]

INCBIN "baserom.gbc", $48000, $4C000 - $48000

SECTION "ROM Bank $13", ROMX[$4000], BANK[$13]

INCBIN "baserom.gbc", $4C000, $50000 - $4C000

SECTION "ROM Bank $14", ROMX[$4000], BANK[$14]

INCBIN "baserom.gbc", $50000, $54000 - $50000

SECTION "ROM Bank $15", ROMX[$4000], BANK[$15]

INCBIN "baserom.gbc", $54000, $58000 - $54000

SECTION "ROM Bank $16", ROMX[$4000], BANK[$16]

StudioTilesGBC:
	INCBIN "gfx/studio/tiles_gbc.2bpp.lz"

INCBIN "baserom.gbc", $58701, $5871d - $58701

StudioMetatilesGBC:
	INCBIN "gfx/studio/metatiles_gbc.bin.lz"
StudioMapGBC:
	INCBIN "data/levels/studio_gbc.vdmap.lz"
StudioTileAttributesGBC:
	INCBIN "gfx/studio/tile_attributes_gbc.bin.lz"
StudioCeilingFloorTilesGBC:
	INCBIN "gfx/studio/ceiling_floor_gbc.2bpp.lz"
StudioCeilingFloorTilemapGBC:
	INCBIN "gfx/studio/ceiling_floor_gbc.tilemap.lz"
StudioCeilingFloorTileAttributesGBC:
	INCBIN "gfx/studio/ceiling_floor_tile_attributes_gbc.bin.lz"

INCBIN "baserom.gbc", $58e87, $59d9d - $58e87

InfogramesCopyrightGBCTiles:
	INCBIN "gfx/infogrames_copyright/background_gbc.2bpp.lz"
InfogramesCopyrightGBCTilemap:
	INCBIN "gfx/infogrames_copyright/background_gbc.tilemap.lz"
InfogramesCopyrightGBCAttributesTilemap:
	INCBIN "gfx/infogrames_copyright/background_gbc.attrmap.lz"

SECTION "ROM Bank $20", ROMX[$4000], BANK[$20]
; force 1MB ROM
