name LolaBarrel

metasprite
palettes 5 0
origin 0 20
mirrorx 8.5
slice 0 0
slice 8 0
slice 16 0
slice 0 16
slice 8 16
slice 16 16
slice 0 32
slice 8 32
slice 16 32

metasprite
palettes 5 0
origin 24 20
mirrorx 32.5
slice 24 0
slice 32 0
slice 40 0
slice 24 16
slice 32 16
slice 40 16
slice 24 32
slice 32 32
slice 40 32

metasprite
palettes 5 0
origin 48 20
mirrorx 56.5
slice 48 0
slice 56 0
slice 64 0
slice 48 16
slice 56 16
slice 64 16
slice 48 32
slice 56 32
slice 64 32
