name ActionHint

metasprite
palettes 6 0
origin -4 7
mirrorx 0.0
slice 4 28
slice 12 28

metasprite
palettes 6 0
origin 22 7
mirrorx 22

metasprite
palettes 6 0
origin 22 7
mirrorx 22

metasprite
palettes 6 0
origin 22 7
mirrorx 22

metasprite
palettes 6 0
origin 22 7
mirrorx 22

metasprite
palettes 6 0
origin 22 7
mirrorx 26.0
slice 28 8
slice 36 8
slice 44 8

metasprite
palettes 6 0
origin 48 7
mirrorx 52.0
slice 52 8
slice 60 8
slice 68 0
