name BoomBarrier

metasprite
palettes 1 0
origin -8 63
mirrorx -4.0
slice 0 64
slice 0 80

metasprite
palettes 1 0
origin 0 63
mirrorx 4.0
slice 8 32
slice 8 48
slice 8 64
slice 8 80

metasprite
palettes 1 0
origin 8 63
mirrorx 12.0
slice 16 16
slice 16 32
slice 16 48
slice 16 64
slice 16 80

metasprite
palettes 1 0
origin 16 63
mirrorx 20.0
slice 24 0
slice 24 16
slice 24 32
slice 24 48
slice 24 64
slice 24 80
